@echo off
echo	F18RESET -- resets all HORNET campaign files
echo
echo	WARNING: This file will destroy all currently saved
echo		 HORNET campaigns! 
echo
echo	Press CONTROL-C to exit or
pause
del *.sqf
del *.mtf
del *.caf
del *.waf
del *.fla
del *.tmp
del *.dmp
del squ*.mif
del dump?.tmp
del dmp*.
del cdump?.tmp
del buff.tmp
del madbuff.tmp
del theater.bin
del mission.mif
del redflag.mif
del vcr.mif
del temp?.*
del gary.dmp
del occupy.map
del *.TRG
del *.TSf
del squad?.SHf
del global.amo
del simdump.*
del harpoon.dat
del local.amo




