@echo off
echo	F30RESET -- resets all FALCON campaign files
echo
echo	WARNING: This file will destroy all currently saved
echo		 FALCON campaigns! 
echo
echo	Press CONTROL-C to exit or
pause
del *.squ
del *.mtv
del *.cam
del *.war
del *.fla
del *.tmp
del *.dmp
del squ*.mis
del dump?.tmp
del dmp*.
del cdump?.tmp
del buff.tmp
del madbuff.tmp
del theater.bin
del mission.mis
del redflag.mis
del vcr.mis
del temp?.*
del gary.dmp
del occupy.map
del *.TRG
del *.TSK
del squad?.SHP
del global.amo
del simdump.*
del harpoon.dat
del local.amo

