@echo off
echo	MIGRESET -- resets all MIG-29 campaign files
echo
echo	WARNING: This file will destroy all currently saved
echo		 MIG-29 campaigns! 
echo
echo	Press CONTROL-C to exit or
pause
del *.sqm
del *.mtm
del *.cmm
del *.wam
del *.flm
del *.tmp
del *.dmp
del squ*.mim
del dump?.tmp
del dmp*.
del cdump?.tmp
del buff.tmp
del madbuff.tmp
del theater.bin
del mission.mim
del redflag.mim
del vcr.mim
del temp?.*
del gary.dmp
del occupy.map
del *.TRm
del *.TSm
del squad?.SHm
del global.amo
del simdump.*
del harpoon.dat
del local.amo


