@ECHO OFF
CLS
ECHO To run this demo, you'll need 4 megabytes of RAM, and approximately
echo 560k free base memory.  Type MELTDOWN to run the game.  If it the
echo game fails to run with a Critical Error, free up more memory by
echo unloading unnecessary TSR programs, such as your mouse driver and
echo SMARTDRV.SYS.  Remember to make a backup copy of your autoexec.bat and
echo config.sys files so you can restore them back to normal after you run
echo the demo.  Thank you for your interest in the 3D Game Creation System!
