type objects\benetton.dat
type  objects\tyrrel.dat
type  objects\williams.dat
type  objects\mclaren.dat
type  objects\arrows.dat
type  objects\jordan.dat
type  objects\pacific.dat
type  objects\forti.dat

type  objects\minardi.dat
type  objects\ligier.dat
type  objects\ferrari.dat
type  objects\sauber.dat

type  objects\baktyre.dat
type  objects\frontyre.dat
type  objects\shadows.dat
type  objects\ghost.dat

type  objects\smallcar.dat
type  objects\smalltyr.dat
