@echo off
echo ÿWAR IN RUSSIA V1.0 README FILE
echo ÿ
echo ÿ
echo ÿSCENARIO EDITIOR HINTS:
echo ÿ
echo ÿThe Scenario Editor you have in War in Russia is a powerful tool. 
echo ÿThis tool will allow you to edit units, HQ's, game map and create new 
echo ÿscenarios. The most difficult aspect of the editor is making new 
echo ÿscenarios. The following steps are the easiest ways we have found here 
echo ÿat SSI to create a scenario.
echo ÿ
echo ÿ1) First remove all units from the map by using the "Remove" option 
echo ÿfrom the Unit Menu. If you put Caps Lock on your  keyboard and hit 
echo ÿthe "R" key will also remove units.
echo ÿ
echo ÿ2) Now set the new frontlines, this can be easily done by first 
echo ÿusing the "Cntl" button in the editor.  You now see part of the map 
echo ÿcovered by grey or red squares.  Now use the "Set Hex" option in the 
echo ÿ"Util Menu", you can now move the cursor (Crosshairs) over the 
echo ÿcolored hexes.  This changes the control of the hexes.  Once you have 
echo ÿmade the changes, use the "Set Map" option to keep the changes.
echo ÿ
echo ÿ3) You now can place units on the map, its best to place the Hq's 
pause
echo ÿfirst, then place the units on the map.  You can fill out the while 
echo ÿplacing them on the map.
echo ÿ
echo ÿ4) Once all units, air formations and HQ's are in place, you'll need 
echo ÿto set up the scenario enviroment. This is done bet using the 
echo ÿfollowing options: 
echo ÿ        1) Game Len: Sets up how long the scenario is to last.
echo ÿ        2) 1st Player: Detirmines who moves first
echo ÿ        3) Set Date: Sets month and year of scenario
echo ÿ        4) Axis & Soviet Obj: Sets up objective cities for both sides
echo ÿ
echo ÿ
echo ÿ
echo ÿNew Sceanrios:
echo ÿ
echo ÿCampaign 44:
echo ÿ       This scenario covers the time period from July 1944 till the 
echo ÿ       end of August 1944.  Starts with the Russian summer offensive 
echo ÿ       against Army Group Center.  Victory conditions as per all 
echo ÿ       other campaign scenarios.
echo ÿ
echo ÿUranus:
echo ÿ        This small scenario covers the southern half of the map only.  
pause
echo ÿ        Begins with the Russian counter offensive around Stalingrad. 
echo ÿ        Scenario starts in November 1942 and lasts till March 1943.
echo ÿ
echo ÿBagration:
echo ÿ        This scenario covers the northern half of the map only.  
echo ÿ        Starts in July 1944 and last till August 1944.   
echo ÿ
echo ÿ
echo ÿCommon Question & Answers:
echo ÿ
echo ÿ1) How does combat work? Why don't all my units show up?
echo ÿ
echo ÿ        While you may have a total of 1000 squads in a formation or 
echo ÿcorp, it really depends on the units Experience and Readiness.  The 
echo ÿgame will make  a roll and that detirmines how many men and tanks 
echo ÿshow up.  This occurs before the actual battle takes place.  If only 
echo ÿa small portion of your force shows up, that means due to lack of 
echo ÿsupply (readiness) or coordination (Experience) prevent the rest 
echo ÿof the force from showing up.
echo ÿ
echo ÿ2) Why can't I create brand new units in the Editor?
echo ÿ
echo ÿ        The game program has only so many slots allocated for units 
pause
echo ÿin the game.  This includes both on map and future reinforcements. 
echo ÿWhile we allow you to rename units, you can't simply make a infantry 
echo ÿdivision into a panzer division by changing its name.
echo ÿ
echo ÿ3) The weather looks wierd, how come I can get mud right after snow?
echo ÿ
echo ÿ        That's because sometimes you first get snow then a warm spell 
echo ÿwill melt the snow to mud.  This happened historically in 1941, 
echo ÿjust before the blizzard hit the Germans.
echo ÿ
echo ÿ4) Why is transfering units so difficult in the game? 
echo ÿ
echo ÿ        It is really a major operation to move whole divisions from 
echo ÿone corp to another. And we felt that the cost in readiness should 
echo ÿreflect both the rail and logistical costs fo moving units around.
echo ÿ
echo ÿ
echo ÿ5) Why can't I edit the weapons, planes and tanks?
echo ÿ
echo ÿ        We had hoped to allow the users to do this but that would 
echo ÿrequire the program to keep seperate track records for the weapons in 
echo ÿthe game. In the end we found simpler to leave the weapons as is.
echo ÿ
pause
echo ÿ6)  I can't seem to destroy enemy units that easily, why is that?
echo ÿ
echo ÿ        If you simply fight units head, you'll find that they will 
echo ÿtend to retreat more often than be destroyed.  What you need to do 
echo ÿis use your armor formations to break through and cut off enemy units. 
echo ÿOnce you have done this, you'll find its a lot easier to destroy 
echo ÿenemy units.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿJKY
echo ÿÿÿ