@cls
@echo ***********************************************************
@echo * To play EXTREME ASSAULT with a Force Feedback Joystick, *
@echo * start the game using the parameter ff.                  *
@echo *                                                         *
@echo * For example: C:\BLUEBYTE\EXTREME\START ff               *
@echo ***********************************************************
@pause
