@echo off
copy .\save\savegame.000 savegame.tmp > nul
copy .\save\values.000   values.tmp   > nul
copy .\save\values1.000  values1.tmp  > nul
copy .\save\values2.000  values2.tmp  > nul
copy .\save\resource.0dd resource.tdd > nul
copy .\save\chest.000    chest.tmp    > nul
copy .\save\resource.0se resource.tse > nul
copy .\save\lchest.000   lchest.tmp   > nul
copy .\save\resource.0cm resource.tcm  > nul
