@echo off
copy .\save\savegame.001 savegame.tmp > nul
copy .\save\values.001   values.tmp   > nul
copy .\save\values1.001  values1.tmp  > nul
copy .\save\values2.001  values2.tmp  > nul
copy .\save\resource.1dd resource.tdd > nul
copy .\save\chest.001    chest.tmp    > nul
copy .\save\resource.1se resource.tse > nul
copy .\save\lchest.001   lchest.tmp   > nul
copy .\save\resource.1cm resource.tcm  > nul
