@echo off
copy .\save\savegame.002 savegame.tmp > nul
copy .\save\values.002   values.tmp   > nul
copy .\save\values1.002  values1.tmp  > nul
copy .\save\values2.002  values2.tmp  > nul
copy .\save\resource.2dd resource.tdd > nul
copy .\save\chest.002    chest.tmp    > nul
copy .\save\resource.2se resource.tse > nul
copy .\save\lchest.002   lchest.tmp   > nul
copy .\save\resource.2cm resource.tcm  > nul
