@echo off
copy .\save\savegame.003 savegame.tmp > nul
copy .\save\values.003   values.tmp   > nul
copy .\save\values1.003  values1.tmp  > nul
copy .\save\values2.003  values2.tmp  > nul
copy .\save\resource.3dd resource.tdd > nul
copy .\save\chest.003    chest.tmp    > nul
copy .\save\resource.3se resource.tse > nul
copy .\save\lchest.003   lchest.tmp   > nul
copy .\save\resource.3cm resource.tcm  > nul
