@echo off
copy .\save\savegame.004 savegame.tmp > nul
copy .\save\values.004   values.tmp   > nul
copy .\save\values1.004  values1.tmp  > nul
copy .\save\values2.004  values2.tmp  > nul
copy .\save\resource.4dd resource.tdd > nul
copy .\save\chest.004    chest.tmp    > nul
copy .\save\resource.4se resource.tse > nul
copy .\save\lchest.004   lchest.tmp   > nul
copy .\save\resource.4cm resource.tcm  > nul
