@echo off
copy .\save\savegame.005 savegame.tmp > nul
copy .\save\values.005   values.tmp   > nul
copy .\save\values1.005  values1.tmp  > nul
copy .\save\values2.005  values2.tmp  > nul
copy .\save\resource.5dd resource.tdd > nul
copy .\save\chest.005    chest.tmp    > nul
copy .\save\resource.5se resource.tse > nul
copy .\save\lchest.005   lchest.tmp   > nul
copy .\save\resource.5cm resource.tcm  > nul
