@echo off
copy .\save\savegame.006 savegame.tmp > nul
copy .\save\values.006   values.tmp   > nul
copy .\save\values1.006  values1.tmp  > nul
copy .\save\values2.006  values2.tmp  > nul
copy .\save\resource.6dd resource.tdd > nul
copy .\save\chest.006    chest.tmp    > nul
copy .\save\resource.6se resource.tse > nul
copy .\save\lchest.006   lchest.tmp   > nul
copy .\save\resource.6cm resource.tcm  > nul
