@echo off
cls
echo Dear Valued Customer:
echo ÿ
echo ÿ
echo Thank you for trying our software products.
echo ÿ
echo ÿ
echo All of our products have been fully tested on IBM PC's. We are confident that
echo they will run on good compatibles. But, because we have no way of knowing just
echo how your system is configured, we cannot be responsible for incompatibilities.
echo ÿ
echo ÿ
echo If you encounter any difficulty in running the software, please call the
echo DIGITAL HORIZONS technical support line printed on the disk package back.
echo It is open for your use between 10 AM and 4 PM Eastern Time, Monday
echo through Friday. If you have a modem, you may call our Technical Support
echo Bulletin Board at (517)393-8387 using 8 Data Bits, No Parity, 1 Stop Bit
echo We have multiple lines supporting all baud rates from 1200-14400 HST V32B
echo open 24 hours a day. We will do our very best to help you.
echo ÿ
echo ÿ
echo Thanks again for trying DIGITAL HORIZONS software. We really do hope that
echo you'll enjoy everything that you find inside!
echo ÿ
pause
cls
echo ÿ
echo ÿ
echo ÿ
echo LIMITED WARRANTY
echo ÿ
echo ÿ
echo The disks in this package are warranted to be readable. DIGITAL HORIZONS
echo hereby disclaims all other warranties for this software, including the
echo warranties of merchantability and fitness for a particular purpose. In no
echo event will DIGITAL HORIZONS be liable for any damages, including any lost
echo profits, lost savings or other incidental or consequential damages arising
echo out of the use or inability to use this software. If any disk is not
echo readable, please return it for an immediate replacement.
echo ÿ
echo ÿ
echo DIGITAL HORIZONS
echo Customer Service Dept.
echo PO Box 1092
echo East Lansing, MI 48826
echo ÿ
echo ÿ
pause
cls
echo Some titles in this package may be shareware. Shareware is a rather novel
echo means of marketing software. It has become extraordinarily popular among
echo authors and end users in the past few years.
echo ÿ
echo Shareware is somewhat like public television...it is software on the honor
echo system. We supply the program and on-disk documentation you need to fully
echo use and evaluate the software. If you like the program and continue to use
echo it on a regular basis, you should then honor the author's registration request.
echo ÿ
echo Shareware is a wonderful concept. You get to use and evaluate the software.
echo When you register, you help to insure a continuing supply of low cost,
echo quality software for your PC. Everybody wins!
echo ÿ
echo ÿ
pause
cls
echo ÿ
echo DIGITAL HORIZONS is a division of SOFSOURCE. We are proud to be an Approved
echo Publisher and Associate Member of The Association of Shareware Professionals.
echo We want to make sure that the shareware principle works for you. If you
echo have any problem with a shareware product acquired through us, please contact
echo us immediately. We will do our very best to rectify that problem. If for
echo some reason we cannot resolve the problem to your satisfaction, the ASP may
echo be able to help you. The ASP Ombudsman can help you resolve a dispute
echo or problem with any ASP member, although they do not provide support for
echo members' products. Please contact us first. Failing that, you can write
echo ASP Ombudsman at PO Box 5786, Bellevue, WA 98006.
echo ÿ
echo ÿ
echo DIGITAL HORIZONS
echo Customer Service Dept.
echo PO Box 1092
echo East Lansing, MI  48826
echo ÿ
echo ÿ
echo This disk collection is Copyright 1990 by DIGITAL HORIZONS. Unauthorized
echo duplication for commercial purposes is strictly prohibited.
echo ÿ
echo ÿ
pause
cls
type disk.doc
