rem this will copy BASICA
rem onto your Game Disk for you.
pause
rem insert your DOS Disk in 
rem Drive B and the Game Disk
rem in Drive A.
rem if you have only one floppy
rem just insert your DOS disk
rem when asked for the 
rem diskette for drive B and
rem insert the Game Disk when
rem asked for the diskette for
rem drive A
pause
copy b:basica.com a:
rem now you may start your game 
rem by typing GO while in DOS
