echo off
echo Ý
echo ÝHere is your copy of Moraff's Pinball Version 7.0. Please play and enjoy this
echo Ý   game make as many backups as you need. This game is supported by those
echo Ý   who use and pay for it. Your support has enabled the developement of
echo Ý   Moraff's Blast II, the first game ever to support 800x600 resolution
echo Ý   as well as Hercules, CGA, EGA and VGA.
echo ÝF3 and F4 can be used to fine tune the speed of the game on fast machines.
echo Ý   Complete instructions are listed on the right hand side of the screen
echo Ý   while you are playing the game.
echo Ý
echo ÝThis version you have purchased has a special feature. If you are tired
echo Ý   of losing without getting enough multiple-ball action, you may launch
echo Ý   a series of balls by hitting the up arrow repeatedly. Please note
echo Ý   that this is cheating, and if you really enjoy an honest challenge
echo Ý   I recommend starting with one ball at a time to see how well you can score.
echo Ý
echo ÝPlease note that MoraffWare now has a complete line of EGA/VGA/Super-VGA
echo Ý   games. All have even better graphics than Moraff's Pinball. To order,
echo Ý   call (800) VGA-GAME.
echo Ý
echo ÝType `PINBALL' to start the game.
echo Ý
echo ÝNOTE: USE OF EXCESS BALLS ON SLOW MACHINES MAY RESULT IN ERRATIC PERFORMANCE!
