@echo off
echo ÿQUICKSTART TUTORIAL
echo ÿ12/22/92
echo ÿ
echo ÿAn Engagement
echo ÿ=============
echo ÿ    The simplest situation you can play is the scenario that pits the 
echo ÿBritish battleship Prince of Wales against the German battleship 
echo ÿBismarck. To get started playing Great Naval Battles: North Atlantic 
echo ÿ1939-1943 quickly, just play along with the following directions. 
echo ÿThese introduce you to the major features of the tactical levels of 
echo ÿthe game.
echo ÿ
echo ÿ    After the opening routine finishes, select "SCENARIO" from the 
echo ÿ"CHOOSE GAME" menu, then select "GERMAN" from the "CHOOSE SIDES" 
echo ÿmenu.  "LOAD" the first Engagement offered, "Gunnery Practice: The 
echo ÿBismarck Toe-to-Toe with the Prince of Wales." If you want some 
echo ÿbackground on this Engagement, read the description on p. 28 of the 
echo ÿmanual.
echo ÿ
echo ÿ    The first station you see is the Flag Bridge, with its large map 
echo ÿdominating the center and left of your screen, and the Ship Control 
echo ÿArea on the right. The game is automatically paused when you get to 
echo ÿthis point (as indicated in the upper left of the map), so feel free 
pause
echo ÿto take a minute to look around.
echo ÿ
echo ÿ    First of all, take a look at the map. In the center you see a 
echo ÿblue line with a white tip and a red square around it. That is the 
echo ÿcurrently active ship, the Bismarck You can tell this by looking in 
echo ÿthe upper right of the screen, at the top of the Ship Control Area 
echo ÿwhere the Name Plaque shows the name. Or, you can move the cursor to 
echo ÿthe box containing the "N" in the upper left portion of the map frame 
echo ÿ(fourth one down), and click the left mouse button. This turns the 
echo ÿname filter on, and the ship's name is displayed next to the icon on 
echo ÿthe map. The other boxes with letters in them are other "filters" 
echo ÿthat turn on and off other kinds of information. We'll check out a 
echo ÿfew others in a bit.
echo ÿ
echo ÿ    Before we do, though, take another look in the upper left of the 
echo ÿmap. Above the word "Paused" you see that the time of day is 8:15 in 
echo ÿthe morning (the game uses a military clock, so 8:15 in the evening 
echo ÿwould be 20:15 hours), and the speed of play is at 1:1 (x1).  This is 
echo ÿ"real time"; one second on your watch equals one second of time 
echo ÿsimulated in the game. If at some points the action seems too slow 
echo ÿfor your taste, you can speed the game clock up by selecting the 
echo ÿ"SPEED" item of the "OPTIONS" menu on the menu bar.
echo ÿ
pause
echo ÿ    "What menu bar?" I hear you cry. Why, the one you call up by 
echo ÿpressing the right mouse button. Do this, move the cursor over the 
echo ÿ"OPTIONS" menu, and click with the left mouse button. You should now 
echo ÿsee the various items you can select here, the game "SPEED" among 
echo ÿthem.  However, it's probably better to take things slow at this 
echo ÿpoint, so click the right mouse button again to get rid of the menus 
echo ÿwithout selecting any item.
echo ÿ
echo ÿ    Looking back at the map, there are two other items of interest 
echo ÿright now. First, in the lower right is a number. This shows the wind 
echo ÿspeed. If the wind speed is greater than 0 knots there would be an 
echo ÿarrow associated with this number. These are useful because a strong 
echo ÿwind can affect the accuracy of your gunnery. If you are firing at 
echo ÿlong range perpendicular to the wind direction, your shells tend to 
echo ÿdrift in the direction the wind is blowing. If you are firing into 
echo ÿthe wind, the spray it whips off the waves degrades your gun's 
echo ÿaccuracy in less predictable ways.
echo ÿ
echo ÿ    The second thing to look for on the map is the grid, the square 
echo ÿmesh superimposed on the blue of the water. You can turn it on and 
echo ÿoff using the "G" filter in the upper left of the map frame. Go ahead 
echo ÿand try it!, but leave it on for now. Each line is 10,000 yards from 
echo ÿits neighbors. Since battleships can fire about 40,000 yards, the 
pause
echo ÿgrid makes it easy to tell whether an enemy ship is in range.
echo ÿ
echo ÿ    You may wonder, "Where is the enemy ship?" The easiest way to 
echo ÿfind it is to zoom the map out, so that it shows a larger area of 
echo ÿocean. You can do this by pressing the up arrow in the very upper 
echo ÿright of the map frame. You can tell that the map has been zoomed out 
echo ÿbecause the grid lines are closer together. They are still 10,000 
echo ÿyards apart, so the area of ocean displayed has gone from 70,000 x 
echo ÿ70,000 yards to 140,000 x 140,000 yards. And there, about 20,000 
echo ÿyards south of the Bismarck, lies the Prince of Wales. You can tell 
echo ÿit's British by its color, and you can tell it's the Prince of Wales 
echo ÿbecause it says so right there on the map (you did leave the name 
echo ÿfilter on, didn't you?).
echo ÿ
echo ÿ    We have met the enemy, but he is not ours. Yet, anyway. Before we 
echo ÿunpause the game so the ships can start blowing the stuffing out of 
echo ÿeach other, let's explore a bit further and form a plan of action. 
echo ÿThe first question is whether the two ships are within range of each 
echo ÿother, which we can learn by turning the "M" filter on (on the left 
echo ÿside of the map frame, remember?), which displays two circles showing 
echo ÿthe maximum range of each ship's big guns. No question here, both 
echo ÿships are well within range of the other. Turn that filter off, and 
echo ÿtry the next one down, the "S" for the secondary armament. Here's 
pause
echo ÿsomething interesting! The Bismarck is just within range of the 
echo ÿPrince of Wales' secondaries, but our secondaries have a somewhat 
echo ÿgreater range. Since the British ship has ten main guns to our eight 
echo ÿ(albeit 14" against 15"), we can gain some advantage by moving a bit 
echo ÿfarther out so that our six port-side 5.9" guns can harass His 
echo ÿHighness while his 5.25" popguns can't touch us.
echo ÿ
echo ÿ    Okay, so how do we do this maneuver? It's time to look at the 
echo ÿShip Controls on the right side of the screen. First of all, check 
echo ÿthe Control Mode Selector, to make sure it's set to "M", for manual 
echo ÿcontrol (if it's set to "A", or automatic mode, none of the controls 
echo ÿbelow have any effect; the computer is in complete control of the 
echo ÿship until you switch the selector to "M" ["No, I don't think that's 
echo ÿa good idea, Dave. I really think you should reconsider, Dave. Daave, 
echo ÿoi dooond theengk eu shuud ...  ]).
echo ÿ
echo ÿ    Whew, that was close. Anyway, now that you have control of the 
echo ÿship, the question is what to do with it. First of all, you want to 
echo ÿmake sure that the main guns are targeted on the Prince of Wales, so 
echo ÿwhen you unpause the game your gunners will begin firing their guns 
echo ÿimmediately.  Move the cursor over the upper box below "Main Target" 
echo ÿand click. A dialog box appears at the top of the map, listing the 
echo ÿ"Pr Wales". Point and click on that, and look for two things. First, 
pause
echo ÿthe name of the enemy ship should appear in the box right below "Main 
echo ÿTarget", and second, a diamond should appear around the enemy ship on 
echo ÿthe map. (If these don't happen, click on the box below "Main Target" 
echo ÿagain and be careful in pointing and clicking on the "Pr Wales". 
echo ÿThere are no points for sinking "NO TARGET".)
echo ÿ
echo ÿ    Next, you should set up the maneuver that brings you out of the 
echo ÿenemy's secondary gun range. You can do this by using the "Course" 
echo ÿcontrols a little above the "Main Target" control you just used. Find 
echo ÿthe number "270" with the arrows pointing in either direction away 
echo ÿfrom it and click on the right arrow. The number will change to 
echo ÿ"271", which means that the Bismarck will alter its course just to 
echo ÿthe north of west (remember, 270 is due West, 180 is due South, and 
echo ÿ90 is due east, and 0/360 is due North on a compass). Since this 
echo ÿbrings us out of range only ever so slowly, keep clicking on that 
echo ÿleft arrow until it reads "300" (if you overshoot, use the left arrow 
echo ÿto bring the number back down). This course should bring the Prince 
echo ÿof Wales' guns out of range quickly, while still keeping it within 
echo ÿthe range of fire of the Bismarck's secondary guns.
echo ÿ
echo ÿ    One final thing before you unpause the game. Click on the right 
echo ÿarrow under "SPEED" until the number reads "30". There's no point 
echo ÿpoking along.
pause
echo ÿ
echo ÿ    Now you're ready for the action to begin. Click the right mouse 
echo ÿbutton to get the menu bar, click on the OPTION menu, and choose the 
echo ÿitem PAUSE GAME. Note that in the future you can also pause and 
echo ÿunpause the game by pressing the hot key combination Alt-P.
echo ÿ
echo ÿ    Almost immediately, you will hear the sound of gunfire, but not 
echo ÿmuch else will happen. This is because the main guns have fired, and 
echo ÿthe shells are in the air. At 20,000 yards, it takes some time for 
echo ÿthem to reach their target. To get a better view of the action, let's 
echo ÿgo to the main gunnery station. Click the right mouse button, then 
echo ÿclick on the STATIONS menu, and then on the MAIN GUN item. As soon as 
echo ÿyou see the new screen hit Alt-P to pause the game for a minute.
echo ÿ
echo ÿ    As you look at this station, note the small version of the map in 
echo ÿthe upper right corner. Since it looks pretty crowded, press twice on 
echo ÿthe down arrow in the upper right of the frame, which zooms it to 
echo ÿabout the right level. Checking out the overhead view at the bottom 
echo ÿof the station you can see that the main guns are pointed south, 
echo ÿwhich is good, since that's where the enemy is. On the other hand, 
echo ÿthere's nothing to be seen in the binoculars in the upper right. The 
echo ÿreason is that they're pointed due north, directly away from the 
echo ÿPrince of Wales. You can see this from the bearing readout above (it 
pause
echo ÿpoints to "0"). Fortunately, the director has already targeted the 
echo ÿPrince of Wales, as you can see by its name in the lower portion of 
echo ÿthe binoculars, so click on the black "L" just to the left of the 
echo ÿoutside view, and when the "L" changes to white, the binoculars 
echo ÿautomatically center on the enemy ship. (This automatic lock is a 
echo ÿhandy feature, but it may cause you problems in future games with 
echo ÿmultiple enemy ships to watch. The left and right arrows on either 
echo ÿside of the outside view normally swing the binoculars to the left 
echo ÿand right, but not when the lock is on. Keep this in mind when you 
echo ÿhave to move between two or three enemy ships in other scenarios!)
echo ÿ
echo ÿ    (By the way, the same is true of the "C", or center, filter on 
echo ÿthe map and the up/down or left/right scroll arrows (triangles) on 
echo ÿthe bottom and right of the frame. While the "C" is on, the map tries 
echo ÿto remain centered between the active ship and its target. When the 
echo ÿ"C" is off, you can scroll all over the place. For now, just leave 
echo ÿthe "C" on.)
echo ÿ
echo ÿ    You can tell the binoculars' automatic lock-on has worked because 
echo ÿthe readout above the binoculars now points to "180". But you still 
echo ÿcan't see much out there! Press the down arrow (triangle) just to the 
echo ÿright of the outside view, and you will see the "X1" in the 
echo ÿbinoculars change to "X2". This means that their magnification has 
pause
echo ÿbeen increased. Sure enough, there in the middle of the outside view 
echo ÿthe black dot changes into a ship!  Press the down arrow again, and 
echo ÿthe ship becomes larger ("X4"). Two more clicks and you'll see a full 
echo ÿsized ship there. Your enemy awaits.
echo ÿ
echo ÿ
echo ÿ    Before you unpause the game, take a moment to see how your crew 
echo ÿhas the gunnery set up. The left hand knob below the binoculars is 
echo ÿset to "BSIDE", which means "Broadside", or that all main guns are 
echo ÿfiring together at the same target. Depending on the number and 
echo ÿlocation of the enemy, you can also set this knob to control the 
echo ÿforward ("FWD") and aft turrets separately. The knob on the right 
echo ÿside is set to "SPOT", which means that the gun crews wait for each 
echo ÿsalvo to hit before firing another.  This avoids wasting ammunition 
echo ÿbefore the exact aim has been determined.  Later, this is switched to 
echo ÿ"FULL", so that each salvo will be sent on its way as soon as it is 
echo ÿloaded. The time to reload is given in the readout to the right of 
echo ÿ"Ready", while the time left before the salvo in the air hits is show 
echo ÿunder "TOT" (for "Time on Target").
echo ÿ
echo ÿ    Now unpause the game and watch the TOT number count down. When it 
echo ÿreaches zero, you will see splashes around the Prince of Wales, and 
echo ÿyou can also see green markings near it on the map. You will probably 
pause
echo ÿalso see splashes near the Bismarck; these are made by the enemy's 
echo ÿshells aimed at you! Immediately, you will hear the roar of your 
echo ÿguns, and see the tongues of flame shoot out from them in the 
echo ÿoverhead view. You may also see the burst of flames in the binoculars 
echo ÿas the enemy fires back at you. Watch your TOT count down again, and 
echo ÿalso keep track of your reload time. As your director acquires the 
echo ÿtarget, the right hand knob should switch to "FULL", and your guns 
echo ÿwill begin firing steadily. You may begin to score some hits, and you 
echo ÿmay begin to suffer some damage as well.
echo ÿ
echo ÿ    Looking at the overhead view, you will notice that your guns are 
echo ÿbegin to point somewhat backwards. This is because your ship is 
echo ÿheading to the northwest, just as you ordered it to. Turn on the "S" 
echo ÿfilter if it is not still on, and check how close you are to that 
echo ÿgoal. Watch your gunnery and messages about the enemy while you wait 
echo ÿfor the Prince of Wales to close the distance between the two of you.
echo ÿ
echo ÿ    Once the enemy ship has closed that distance, his secondary guns 
echo ÿopen up. Pause the game and use the menus to go to the Navigation 
echo ÿStation at this point. You want to turn the Bismarck away from the 
echo ÿPrice of Wales' secondaries' range. At the navigation station, switch 
echo ÿthe Control Mode (to the left of the ship's name) to "M" for manual, 
echo ÿand then click on the control labeled "BRG" just below the "HDG" 
pause
echo ÿreadout, which should change the letters from gray to red, while the 
echo ÿred letters "RDR" below it change to gray. This changes your control 
echo ÿmechanism from the rudder ("RDR") to the bearing controls, which are 
echo ÿboth the compass and the readout with the arrows at the bottom of the 
echo ÿstation labeled "BRG". You can use the bearing controls to enter the 
echo ÿexact course you want the ship to turn to, but at this point use the 
echo ÿcompass instead. Click on the "W", and the blue line in the compass 
echo ÿpoints to it; the "BRG" readout changes to "270". Now that we have 
echo ÿclosed the gap between the two ships just enough, it is time to 
echo ÿswitch back to heading due west. The "HDG" readout of "300" indicates 
echo ÿthat the ship is still headed northwest, but once you unpause the 
echo ÿgame, it gradually swings to the desired direction.
echo ÿ
echo ÿ    Before you resume the battle, this would be a good time to check 
echo ÿfor damage. Use the menus to switch to the Damage Station, which 
echo ÿshows the condition of your ship. At this point you should leave the 
echo ÿstation on automatic, but return here periodically to keep tabs on 
echo ÿthe health of your vessel.
echo ÿ
echo ÿ    Now go to the Air Ops Station to arm your float plane. Once this 
echo ÿplane is launched (in about 30 minutes) this both improves the 
echo ÿaccuracy of your gunnery and reduces the danger of the plane going up 
echo ÿin a burst of aviation fuel from a shell hit. Click on the left-most 
pause
echo ÿbox above the airplane information and illustration, and select the 
echo ÿPrince of Wales to be the target. Next, click on the box just to the 
echo ÿright of the first box (which now should say "Pr Wales") and it will 
echo ÿchange from "NONE" to "SHADOW". Press "READY", and the button will 
echo ÿchange to "ARMING". Once you unpause the game the crew preps the 
echo ÿaircraft for launch. When the plane is ready, you must come back here 
echo ÿand click on the "LAUNCH" button (the "ARMING" button changes names 
echo ÿon this screen depending on the status of the aircraft). When 
echo ÿlaunched, the plane circles around your enemy and reports on the 
echo ÿaccuracy of your guns.
echo ÿ
echo ÿ
echo ÿ    After resuming play, return to the Main Gunnery screen and watch 
echo ÿthe action. You should be able to follow the exchange of gunfire, 
echo ÿwhile seeing your ship move to a westerly course on the map. You 
echo ÿshould eventually see your plane move toward the enemy, and your guns 
echo ÿshift to point off the beam. The two ships will continue to pound at 
echo ÿeach other, and you can watch the rhythm of reloading, TOT, and the 
echo ÿgradual expenditure of ammunition. Try moving to the various stations 
echo ÿlisted in the menu, and try out some of the other choices listed 
echo ÿthere too. Remember that the game pauses while you read the 
echo ÿbackground material contained in the "BRIEFINGS", so you may want to 
echo ÿsample some of these as well. If you want to become more involved in 
pause
echo ÿthe action, switch more stations to manual (the Damage Control 
echo ÿStation usually requires considerable attention). Or, if you want, 
echo ÿjust turn up the speed to "X8". Depending on the fortunes of war, it 
echo ÿshould not be too long before one ship or the other slips to a watery 
echo ÿgrave.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿAn Operation
echo ÿ============
echo ÿ    To help get you started quickly with the Operational and Campaign 
echo ÿlevel games, this tutorial walks you through the first portion of a 
echo ÿsortie by the battleship Bismarck.
echo ÿ
echo ÿ    After the introductory routine finishes, select "CAMPAIGN" from 
echo ÿthe "CHOOSE GAME" menu, the select "BRITISH" from the "CHOOSE SIDES" 
echo ÿmenu, and then click "Next" to "LOAD" the Operation named, "Operation 
echo ÿRheinubung: the Bismarck Sets Sail." If you want some background on 
echo ÿthis Operation, check out the description on p. 39 of the manual.
echo ÿ
echo ÿ    Once again, as the game begins, you see a large map, but this one 
echo ÿis on the wall of the Admiralty building. Since the game is paused, 
pause
echo ÿyou should take this opportunity to become acquainted with the 
echo ÿdisplays and controls before the action starts.
echo ÿ
echo ÿ    Looking at the map, you can see that it encompasses the entire 
echo ÿNorth Atlantic. Surrounding it are the familiar controls in the 
echo ÿframe: the scroll arrows on the right and at the bottom, the zoom and 
echo ÿunzoom arrows in the upper right, and the filters in the upper left. 
echo ÿDon't bother with the scroll and zoom controls at the moment -- they 
echo ÿwork like the ones on the tactical map -- but the filters are worth a 
echo ÿlook. Three are already selected: "B", "C", and "T", which stand for 
echo ÿBases, Convoys, and Task Forces. Click on "B" a few times and see how 
echo ÿthe squares turn on and off; these are yours and the enemy's bases. 
echo ÿDo the same with "C", and you can see where your convoys are and how 
echo ÿthey're represented. The same goes for "T", although you may not see 
echo ÿmuch happen. There is a Task Force already in Gibraltar, which is the 
echo ÿBritish (red) base in the lower-right side of the map, between Spain 
echo ÿand Africa. The Task Force is the bright red "T" against the darker 
echo ÿred of the square representing the Base.
echo ÿ
echo ÿ    When you toggled the Bases on and off, another set of icons 
echo ÿtoggled as well, the "P"s in the ocean between Greenland, Iceland, 
echo ÿand Northern Scotland. These are Patrol Zones, areas where the Royal 
echo ÿNavy keeps ships constantly on station to intercept any German 
pause
echo ÿraiders trying to move through these gaps into the North Atlantic 
echo ÿshipping lanes.  Together, these four elements -- the Bases, Task 
echo ÿForces, Patrol Zones, and Convoys -- are the primary elements of your 
echo ÿcommand. They contain individual ships, of course, and you will often 
echo ÿmove vessels between them, but they are the units with which you 
echo ÿmainly work. You will almost always want to keep all three filters 
echo ÿon.
echo ÿ
echo ÿ    Before you begin giving orders to them, however, there are a few 
echo ÿother filters worth examining. Specifically, the "S", or Search 
echo ÿfilter, shows the range of air searches from each base. As you can 
echo ÿsee, by May, 1941, the entire northeastern section of the ocean was 
echo ÿpretty well covered, but if the enemy breaks out, there is plenty of 
echo ÿocean down south for him to hide in. And remember, the searches are 
echo ÿmost effective near the center of a circle, and become less useful 
echo ÿtowards its periphery. Again, by May, 1941, the immediate area 
echo ÿbetween Greenland and the UK is pretty well covered, but even the 
echo ÿhinterland south of Iceland and west of Ireland is less well 
echo ÿpatrolled than it first appears.
echo ÿ
echo ÿ    Turning off the "S" and turning on the "A" filter shows you a 
echo ÿnumber of much smaller circles. These depict the range of shore-based 
echo ÿattack aircraft. Any ship venturing within these circles quickly find 
pause
echo ÿitself at the center of a swarm of angry aircraft. Avoid these places.
echo ÿ
echo ÿ    Okay, now it's time to assess the situation. Since the Germans 
echo ÿwill be coming out of the North Sea, there's no point viewing the 
echo ÿwhole North Atlantic, so click on the Zoom-in (down) arrow in the 
echo ÿupper-right of the map frame one time, which zooms your view in on 
echo ÿthe area from Norway in the upper-right to Germany in the 
echo ÿlower-right, with the United Kingdom, Ireland and the Normandy coast 
echo ÿbetween in the middle. It is through here that the Germans must move. 
echo ÿ(The English Channel between southern Britain and the European 
echo ÿcontinent is guarded by mine-fields, coastal craft, and airplanes, 
echo ÿsymbolized by the colored blotch on the water. Similar defenses guard 
echo ÿother areas of the map, with the color of the blotch indicating who 
echo ÿis defending, and thus implying who will be hurting if they enter.) 
echo ÿWe'll come back to this close-in view later, for now, zoom back to 
echo ÿthe original view of the whole North Atlantic.
echo ÿ
echo ÿ    Begin by checking on your Patrol Zones. To check on all ships 
echo ÿassigned to patrol duty, call up the menu bar by clicking on the 
echo ÿright mouse button, click with the left button on REPORTS and select 
echo ÿthe PATROL POOL item. This brings up the Patrol Pool Report, showing 
echo ÿthat five cruisers are currently available for patrols. Two each are 
echo ÿassigned to the western and central gaps, and one supplements the air 
pause
echo ÿpatrols and strike aircraft covering the east. Click on "EXIT" to 
echo ÿreturn to the map.
echo ÿ
echo ÿ    To get another view of the patrol situation, click on the 
echo ÿleft-most Patrol Icon itself. This brings up the Control Display for 
echo ÿthe Greenland-Iceland gap. Since two cruisers is plenty for the 
echo ÿmoment, there is no need to make any adjustments, but this is where 
echo ÿyou can specify more or fewer craft of each type in future games, and 
echo ÿwhere you go to take ships away from the zone in an emergency.
echo ÿ
echo ÿ    Returning to the main map, it's time to get down to business. You 
echo ÿknow that the Bismarck is about to sortie, so it would be good to get 
echo ÿsome of your ships at sea. The question is, where are they? Go to the 
echo ÿmenu and call up the ALL SHIPS report, and you will see that most of 
echo ÿyour battleships are at Scapa Flow (with some at Gibraltar/Force H), 
echo ÿwhile many of the lighter craft are already at sea, but are committed 
echo ÿto patrol duty and escort service.
echo ÿ
echo ÿ    The question now is, "Where is Scapa Flow?" Hit "EXIT" to return 
echo ÿto the map, and turn the "N", name, filter on. Now you can see Scapa 
echo ÿFlow, conveniently located at the entrance to the North Sea. Click on 
echo ÿthe square icon, and you move to the Base Overview Display. At the 
echo ÿtop you can see that the base has 10 Swordfish ready to attack if the 
pause
echo ÿBismarck should stray within range, and 10 Catalinas with which to 
echo ÿsearch. In the middle of the screen is the long list of ships based 
echo ÿhere, and at the bottom are the buttons used to undertake various 
echo ÿactivities.
echo ÿ
echo ÿ    At the moment, you want to get a Task Force under way, so click 
echo ÿon the "FORM TF" button (the others let you add ships to the Patrols 
echo ÿand Escort Pools or send ships into repair). The screen now divides, 
echo ÿwith the ship list on the left and a blank list labeled "NEW TF" on 
echo ÿthe right. To begin forming the new Task Force, click on the 
echo ÿbattleship Hood (a BB), and it will jump from the left-hand list to 
echo ÿthe right. Click again on the Prince of Wales (BB), the Kenya (CA, a 
echo ÿcruiser), the Electra (DD, a destroyer), and the Aschates (DD), and 
echo ÿleave the rest.
echo ÿ
echo ÿ    Now click on "ORDERS", and you move to the Task Force Overview 
echo ÿDisplay, exactly the same Display you would see if you had clicked on 
echo ÿa Task Force icon on the map. This is similar to the Base Overview 
echo ÿDisplay, showing the aircraft controls at the top (which would have 
echo ÿairplanes were there an aircraft carrier with these ships), the ship 
echo ÿroster in the middle, and the activity buttons below.
echo ÿ
echo ÿ    Since we want to order this Task Force out to sea, click on 
pause
echo ÿ"PLOT". This brings up the strategic map again, but this time with 
echo ÿsome controls on the right side. But the main control is the map 
echo ÿitself. To order the Task Force (the bright red "T" on top of the 
echo ÿdarker red square for Scapa Flow) to move, simply point at the map 
echo ÿand click. Specifically, point to a place just below the "V" in 
echo ÿ"Reykjavik" in Iceland and click, and a yellow line appears. This is 
echo ÿthe path the Task Force will follow.  Furthermore, the number next to 
echo ÿ"Waypoint" in the controls to the right goes from "0" to "1", 
echo ÿindicating that one leg of the journey has been plotted. Each Task 
echo ÿForce can be given up to ten waypoints, and if you make a mistake and 
echo ÿwant to start over, you just have to click on "CLEAR".
echo ÿ
echo ÿ    In this case, the move to Iceland should suffice, so click on 
echo ÿ"DONE" and return to the Task Force Overview Display. There is one 
echo ÿmore thing to do here; in the upper left area are controls for the 
echo ÿTask Force's speed. It is now set for cruise speed, 14 knots, which 
echo ÿis economical, but may not get us there in time if the Bismarck 
echo ÿdashes for the Greenland-Iceland straits. Therefore, click on "MAX", 
echo ÿand the speed should jump to 28.
echo ÿ
echo ÿ    Before you start the game, there is one other assignment you 
echo ÿshould make. Click on the Convoy icon (the flattened "C") to the west 
echo ÿof Ulster, which brings up the Convoy Overview Display. You can see 
pause
echo ÿthat five destroyers are escorting this convoy. To increase your 
echo ÿchances of catching the Bismarck, click on "DETACH", which brings up 
echo ÿthe New Task Force Display. This process works just like forming a 
echo ÿTask Force at a base; just click on each ship in turn to transfer it 
echo ÿfrom the Convoy to the Task Force. Once all five ships have been 
echo ÿtransferred, click on "ORDERS" to move to the Task Force Overview 
echo ÿDisplay, and then click on "PLOT". Point to a position just southwest 
echo ÿof the little island about half-way between Britain and Iceland and 
echo ÿclick; this becomes the Task Force's destination.  Click on "DONE" to 
echo ÿreturn to the Task Force Overview Display, set the speed to "MAX", 
echo ÿand "EXIT" to the main map. Now would be a good time to zoom in again 
echo ÿon the North sea.
echo ÿ
echo ÿ    You are now ready to unpause the game. Hit Alt-P and watch as 
echo ÿtime begins to pass. You will get messages indicating when the enemy 
echo ÿhas been spotted and see icons marking their location. You will also 
echo ÿget various messages about the status of your own forces. Turn on the 
echo ÿ"M" ("Movement") filter, which shows where you have plotted your Task 
echo ÿForces to move, and watch as they move toward their destination. 
echo ÿBefore much time passes, click on Scapa Flow again and make another 
echo ÿTask Force including the King George V, the Repulse, the Victorious, 
echo ÿthe Edinburgh, the Anthony, and the Echo, and plot it to move at 
echo ÿmaximum speed to a point in between the destinations of the other two 
pause
echo ÿforces.
echo ÿ
echo ÿ    If the Forces reach their destinations without the Bismarck 
echo ÿhaving been spotted, immediately order Force B (the one with the 
echo ÿHood) around to off the coast of Reykjavik, and order the newest one 
echo ÿ(Force D) to where Force B had been. Now all you can do is wait for 
echo ÿthe German to show himself, This he will do eventually, most likely 
echo ÿto one or two of your patrolling cruisers. When he does, order them 
echo ÿto "SHADOW" him, and plot your Task Forces to intercept. Remember to 
echo ÿzoom the map in steadily; what appear to be minor distances at the 
echo ÿhigher zoom levels take on a whole new aspect when viewed close-up.
echo ÿ
echo ÿ    Once one of your Task Forces intercepts the enemy, the game moves 
echo ÿto the tactical level. If you succeed in sinking the Bismarck, the 
echo ÿgame will be over and you will have won; if it gets by, he may well 
echo ÿbag one or more convoys, and at the least you will have to play 
echo ÿcat-and-mouse across the wide North Atlantic. You can still win, but 
echo ÿthe struggle will be much tougher. Whatever happens, though, you 
echo ÿshould be able to take the lead from here.
echo ÿ
echo ÿTutorial written by Ed Bever PhD
echo ÿRevised for Version 1.1 by Tom MacDevitt
echo ÿÿÿ