echo off
cls
echo                    THEXDER II FIREHAWK README FILE
echo                            September 24,1990
echo.
echo  The intention of this Readme file is to inform you of possible 
echo  problems with the program and updates to the documentation. 
echo.
echo  COPY PROTECT : THEXDER II copy protect will ask you to type
echo                 in a word found on a given page, line and word 
echo                 position of your manual. When counting lines,
echo                 be sure to include blank lines and title lines.
echo.    
echo.
pause
echo.
echo.
echo  TANDY 1000 TL : Using your joystick
echo.
echo                  If you wish to play using your Tandy Joystick,
echo                  select the following while running "INSTALL".
echo                  (Refer to your users manual for details on how
echo                  to run "INSTALL".)
echo.
echo                       - Music capability, select "TANDY 1000 Series"
echo                         NOTE: do not select "TANDY 1000 TL Series"
echo.
echo                       - Joystick use, select "YES"
echo.
echo                  If you do not wish to play using your Tandy joystick,
echo                  then you may select either "TANDY 1000 Series" or
echo                  "TANDY 1000 TL Series" for music capability.
echo                  However, the "TANDY 1000 TL Series" will give you
echo                  superior sound effects.
echo.
pause

