CLS
@ECHO OFF
ECHO =============================================================================
ECHO INSTALACION DEEP RED				   JUEGOS PARA TU PC No. 5
ECHO =============================================================================
ECHO.
ECHO.
ECHO Instalando, espere por favor.
MD C:\DEEP> NUL
XCOPY a: c:\DEEP /s > NUL
C:
CD\
CD C:\DEEP > NUL
pkunzip -d DEEP.zip > nul
del DEEP.zip > nul
cls
echo Para jugar , teclea DEEP y despu‚s pulsa ENTER.



