echo off
cls
echo 		##########################################
echo 		#                                        #
echo 		#                                        #
echo 		#                                        #
echo 		#                                        #
echo 		#    The Magnetic Scrolls Collection     #
echo 		#               Volume 1                 #
echo 		#                                        #
echo 		#     (C) 1991 Magnetic Scrolls Ltd.     #
echo 		#                                        #
echo 		#                                        #
echo 		#    Published By Virgin Mastertronic    #
echo 		#                                        #
echo 		#                                        #
echo 		#                                        #
echo 		##########################################
game
