@echo off
echo .                                                .
echo .   (c)opyrights 1994 RedCat Software            .
echo .                                                .
echo .  LEES BIJ PROBLEMEN, VRAGEN EN VOOR MEER INFO  .
echo .         HET BESTAND: LEESMIJ                   .
echo .                                                .
echo .                                                .
mb1 %1
