ECHO OFF
CLS
ECHO          ***********************************************************
ECHO          *                                                         *
echo          *        $$$$$     WELCOME TO MEGAGOPOLY     $$$$$        *
ECHO          *                       RELEASE 1.1                       *
ECHO          *                                                         *
echo          *                                                         *
echo          *     If you enjoy this program, please send $18.00       *
echo          *     to become a registered user and receive a users'    *
echo          *     manual with instructions, strategies and tips       *
echo          *     for winning.  You will also receive notice of       *
echo          *     future product updates and discounts on new         *
echo          *     products.  Foreign orders please add $5.00 for      *
echo          *     shipping costs.                                     *
echo          *                                                         *
echo          *                                                         *
echo          *                                                         *
echo          *                Copyright (c) 1986, 1991                 *
echo          *            Visual Data Communications Corp.             *
echo          *                     P.O. Box 40956                      *
echo          *                 Indianapolis IN 46240                   *
echo          *                                                         *
echo          ***********************************************************
pause
meg7




 
