echo off
echo ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
echo ³  Mycroft Door Installation  ³
echo ³  Mycroft Systems - 10/10/89 ³
echo ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
echo 
echo Notice...
echo For this installation program to run, all install programs (.EXE) from
echo the MYCROFT.ZIP door installation program must be accessable via the PATH=
echo environment variable.  PKUNZIP.EXE 1.01 or newer must also be available to
echo run....

echo Ready to install door...
pause
echo Scanning installation module, please stand by...
do @install

