echo off
cls
set dos4g=quiet
config setdir

if errorlevel 23 goto drivez
if errorlevel 22 goto drivey
if errorlevel 21 goto drivex
if errorlevel 20 goto drivew
if errorlevel 19 goto drivev
if errorlevel 18 goto driveu
if errorlevel 17 goto drivet
if errorlevel 16 goto drives
if errorlevel 15 goto driver
if errorlevel 14 goto driveq
if errorlevel 13 goto drivep
if errorlevel 12 goto driveo
if errorlevel 11 goto driven
if errorlevel 10 goto drivem
if errorlevel 09 goto drivel
if errorlevel 08 goto drivek
if errorlevel 07 goto drivej
if errorlevel 06 goto drivei
if errorlevel 05 goto driveh
if errorlevel 04 goto driveg
if errorlevel 03 goto drivef
if errorlevel 02 goto drivee
if errorlevel 01 goto drived
echo Fatal error!!! No Executable Drive Found!!!!!
goto end

:drivez
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive Z ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
z:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc

:drivey
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive Y ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
y:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivex
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive X ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
x:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivew
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive W ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
w:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivev
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive V ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
v:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driveu
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive U ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
u:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivet
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive T ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
t:
cd \mcoil      
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drives
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive S ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
s:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driver
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive R ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
r:
cd \mcoil      
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driveq
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive Q ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
q:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivep
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive P ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
p:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driveo
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive O ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
o:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driven
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive N ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
n:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivem
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive M ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
m:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivel
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive L ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
l:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivek
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive K ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
k:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivej
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive J ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
j:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivei
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive I ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
i:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driveh
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive H ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
h:
cd \mcoil      
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:driveg
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive G ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
g:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivef
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive F ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
f:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drivee
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive E ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
e:
cd \mcoil      
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc


:drived
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
echo ± Please Wait...                ±°
echo ± About To Execute From Drive D ±°
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°
echo  °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
config instdir
d:
cd \mcoil
if errorlevel 24 goto candyz
if errorlevel 23 goto candyy
if errorlevel 22 goto candyx
if errorlevel 21 goto candyw
if errorlevel 20 goto candyv
if errorlevel 19 goto candyu
if errorlevel 18 goto candyt
if errorlevel 17 goto candys
if errorlevel 16 goto candyr
if errorlevel 15 goto candyq
if errorlevel 14 goto candyp
if errorlevel 13 goto candyo
if errorlevel 12 goto candyn
if errorlevel 11 goto candym
if errorlevel 10 goto candyl
if errorlevel 09 goto candyk
if errorlevel 08 goto candyj
if errorlevel 07 goto candyi
if errorlevel 06 goto candyh
if errorlevel 05 goto candyg
if errorlevel 04 goto candyf
if errorlevel 03 goto candye
if errorlevel 02 goto candyd
goto candyc

:candyz
coil z: %1
z:
cd \coil
goto end
:candyy
coil y: %1
y:
cd \coil
goto end
:candyx
coil x: %1
x:
cd \coil
goto end
:candyw
coil w: %1
w:
cd \coil
goto end
:candyv
coil v: %1
v:
cd \coil
goto end
:candyu
coil u: %1
u:
cd \coil
goto end
:candyt
coil t: %1
t:
cd \coil
goto end
:candys
coil s: %1
s:
cd \coil
goto end
:candyr
coil r: %1
r:
cd \coil
goto end
:candyq
coil q: %1
q:
cd \coil
goto end
:candyp
coil p: %1
p:
cd \coil
goto end
:candyo
coil o: %1
o:
cd \coil
goto end
:candyn
coil n: %1
n:
cd \coil
goto end
:candym
coil m: %1
m:
cd \coil
goto end
:candyl
coil l: %1
l:
cd \coil
goto end
:candyk
coil k: %1
k:
cd \coil
goto end
:candyj
coil j: %1
j:
cd \coil
goto end
:candyi
coil i: %1
i:
cd \coil
goto end
:candyh
coil h: %1
h:
cd \coil
goto end
:candyg
coil g: %1
g:
cd \coil
goto end
:candyf
coil f: %1
f:
cd \coil
goto end
:candye
coil e: %1
e:
cd \coil
goto end
:candyd
coil d: %1
d:
cd \coil
goto end
:candyc
coil c: %1
c:
cd \coil

:end
