echo *    BOATING SIMULATOR HARD DISK SYSTEM SETUP ERROR    *
echo ***      CANNOT FIND FILES...LOAD NOT CORRECT !      ***
echo Please check MASTER GUIDE, fix problem, then try again.
echo   Check that Install worked, and files are loaded on C:
echo   Check that ASSIGN.COM is in DOLPHIN Directory, or
echo        if AUTOEXEC.BAT has PATH statement to DOS.
echo   If using RAMDISK...Check if setup is OK, and if RAMDISK
echo        is set up as Drive D: in CONFIG.SYS 
echo ***    CHECK INSTALLATION CONSIDERATIONS IN MANUAL !  ***
echo NOTE: MOST installs work fine, and multiple intallations
echo usually do not fix the problem; if files are in the DOLPHIN
echo Directory, diagnose the problem rather than reinstalling.
assign
CD\

