@echo off
echo The following text describes the current version of the game.
echo It is a longer file than the previous "readme" files, and
echo therefore will be presented to you a screen-ful at a time.
echo At the end of the screen of text, the display will pause,
echo waiting for some action from you.  Pressing any key will
echo cause the next screen's worth of text to be displayed.
echo Pressing the Control-C key will terminate the display
echo and return you to the command line prompt.
echo .
Pause Press any key to continue
more <readme.doc
