ECHO OFF
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ When this file is on your hard drive with your other BAT files and บ
ECHO บ CleanUp is in its own directory, no changes should be required.    บ
ECHO บ Please save a copy if you adapt this file for your system.  Chris  บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
REM   The above message is pushed off screen if there are no errors.
BROWSE CLEANUP\CLEANUP.DOC
CLS
CD\CLEANUP
CLEANUP.EXE
CD\
