echo off
cls
echo                      ************************************
echo                      *                                  *
echo                      * Summer Olympiad (c)1988 Tynesoft *
echo                      *                                  *
echo                      *       All Rights Reserved        *
echo                      *                                  *
echo                      ************************************
realdos
titleseq
:gameloop
gofor
tst2
sks
fencing
trp
ev3
ev4
goto gameloop
