copy start.com %1
copy cga.com %1
copy tandy.com %1

copy game.exe %1

copy TITLE.DAT %1
copy PANNEL.DAT %1
copy CLIPS.DAT %1
copy OBJPIC.DAT %1
copy MISSLE.DAT %1
copy STOKENS.DAT %1
copy UTOKENS.DAT %1
copy sbits.dat %1

copy MPL0.DAT %1

copy MSVA.DAT %1
copy MSVB.DAT %1
copy MSVC.DAT %1
copy MSVF.DAT %1
copy MSVH.DAT %1
copy MSVI.DAT %1
copy MSVJ.DAT %1
copy MSVK.DAT %1
copy MSVL.DAT %1
copy MSVM.DAT %1
copy MSVN.DAT %1
copy MSVO.DAT %1
copy MSVP.DAT %1
copy MSVQ.DAT %1
copy MSVR.DAT %1

copy install.exe %1
copy *.ins %1
