CLS
@ECHO OFF
ECHO =============================================================================
ECHO INSTALACION HOT SPEED				   JUEGOS PARA TU PC No. 4
ECHO =============================================================================
ECHO.
ECHO.
ECHO Instalando, espere por favor.
MD C:\hspeed> NUL
XCOPY a:*.* c:\hspeed /s > NUL
C:
CD\
CD C:\hspeed > NUL
pkunzip -d hotspeed.zip > nul
del hotspeed.zip > nul
cls
echo Para jugar , teclea HOTSPEED y despu‚s pulsa ENTER.



