echo off
cls
echo зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
echo Ё You must type in the game program name then press enter       Ё
echo Ё to start it.                                                  Ё
echo цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
echo Ё     TYPE IN                   TO RUN                          Ё
echo Ё                                                               Ё
echo Ё      big2                     Big 2                           Ё
echo Ё      klondike                 Klondike Solitaire              Ё
echo Ё      mahjsol                  Mahjong Solitaire               Ё
echo Ё      millebrn                 Mille Bornes                    Ё
echo Ё      monopoly                 Monopoly                        Ё
echo Ё                                                               Ё
echo цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
echo Ё If you enjoy the TEGL games please register!                  Ё
echo юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды


