@echo off
echo **  
echo **  Zork Nemesis for DOS requires VESA BIOS version 1.2 or later.
echo **  If your video card is not compliant with 1.2 BIOS we recommend
echo **  trying UniVBE, a software BIOS emulator for your video card.  
echo **    
echo **  You may try an unregistered evaluation copy of UniVBE by typing
echo **  'INSTALL' from the UNIVBE directory of Zork Disc I.
echo **    
echo **  For more information, consult the README.TXT in the same
echo **  directory.
echo **  

