copy a:fb.exe c:\firebrg
copy a:egavga.bgi c:\firebrg
echo Please insert 'Master B' disk into drive A
pause
copy a:fbstrat.ega  c:\firebrg
copy a:fbtactic.ega  c:\firebrg
copy a:fbscreen  c:\firebrg
copy a:fbsymbol.img  c:\firebrg
copy a:fbsymbol.sym  c:\firebrg
copy a:fbtut  c:\firebrg
copy a:fb3nov  c:\firebrg
copy a:fb5dec  c:\firebrg
copy a:fb15nov  c:\firebrg
copy a:fb  c:\firebrg
cls
echo Your FireBrigade system is now copied
echo on
