echo off
cls
echo ***** PLEASE INSERT YOUR SCENARIO DISK IN DRIVE A *****
pause
cls
del a:\scenario\castlesg.wcs
del a:\scenario\deltafrc.wcs
del a:\scenario\meusabus.wcs
del a:\scenario\beta4.wcs
del a:\scenario\fuldagap.wcs
del a:\scenario\1stbulrn.wcs
del a:\scenario\2xariver.wcs
cls
echo ............................................
echo .   YOU NOW HAVE A USABLE SCENARIO DISK    .
echo .   THAT WILL HOLD UP TO 7 SCENARIOS OR    .
echo .   SAVE GAMES.  THE SCENARIO DISK IS A    .
echo .   NORMAL GAME DISK WITHOUT THE STANDARD  .
echo .                SCENARIOS                 .
echo ............................................
pause
echo on
cls
