@echo off
cls
echo -   Iron Cross Addendum   -
echo 
echo Iron Cross attempts to support as many sound cards
echo as possible. However we can only perform so many
echo miracles. If you are having problems with your
echo sound or music try using Sound Blaster.
echo 
echo Iron Cross utilizes the best sound technologies
echo available. Whenever you combine the best in Sound
echo and Music you inevitably have problems. The Gravis
echo UltraSound card is a wonderful card, but due to a
echo conflict, not solved before we shipped, you can only
echo play Iron Cross on the UltraSound if you select Sound
echo or Music, not both. To do this run the INSTALL program
echo and select UltraSound for Sound and NONE for Music or
echo vice-versa. Although Iron Cross has great music we   
echo feel that you will get more enjoyment from the Sound  
echo and Sound Effects.
echo 
pause
echo If you are having any problems that you are unable
echo to solve, we would be happy to assist you on our
echo Technical Support Hotline at (818)-889-5650.
echo 
echo New World Computing, Inc.
echo P.O. Box 4302
echo Hollywood, CA 90078-4302
echo (818)-889-5650 (Tech Support / Hint Line)
echo (818)-889-5684 (24 hour BBS)
echo 
