echo off
cls
echo                         ษออออออออออออออออออออออออออออออออออออป
echo                         บ            MAYDAY SQUAD            บ
echo                         บ           is now loading           บ
echo                         บ                                    บ
echo                         บ       Copyright TYNESOFT 1989      บ
echo                         บ         All rights reserved        บ
echo                         บ      Programmed by Philip Scott    บ
echo                         บ  Graphics by D.Mowbray and Nemesis บ
echo                         บ      Music by David Whittaker      บ
echo                         บ   Game Design by SUBWAY SOFTWARE   บ
echo                         บ                                    บ
echo                         บ  Controls:                         บ
echo                         บ        Up arrow-up                 บ
echo                         บ      Down arrow-down               บ
echo                         บ      Left arrow-left               บ
echo                         บ     Right arrow-right              บ
echo                         บ           Space-fire/select        บ
echo                         บ               1-cursor left        บ
echo                         บ               2-cursor middle      บ
echo                         บ               3-cursor right       บ
echo                         บ                                    บ
echo                         ศออออออออออออออออออออออออออออออออออออผ
load
:gameloop
may2
goto gameloop

:helloween
b:
goto gameloop
