echo off
cls
echo                         ษออออออออออออออออออออออออออออออออออออป
echo                         บ            MAYDAY SQUAD            บ
echo                         บ           is now loading           บ
echo                         บ                                    บ
echo                         บ       Copyright TYNESOFT 1989      บ
echo                         บ         All rights reserved        บ
echo                         บ      Programmed by Philip Scott    บ
echo                         บ  Graphics by D.Mowbray and Nemesis บ
echo                         บ  Game Concept by SUBWAY SOFTWARE   บ
echo                         บ                                    บ
echo                         ศออออออออออออออออออออออออออออออออออออผ
load
:gameloop
may2
goto gameloop

