echo off
cls
echo                         ษออออออออออออออออออออออออออออออออออออป
echo                         บ            MAYDAY SQUAD            บ
echo                         บ       Copyright TYNESOFT 1989      บ
echo                         บ         All rights reserved        บ
echo                         บ       HARD DISK INSTALLATION.      บ
echo                         บ           Copying Disk 1           บ
echo                         ศออออออออออออออออออออออออออออออออออออผ
c:
md\maydaysq
cd\maydaysq
copy a:*.*>nul
cls
echo                         ษออออออออออออออออออออออออออออออออออออป
echo                         บ            MAYDAY SQUAD            บ
echo                         บ  Program Installed.                บ
echo                         บ  Put game disk in drive A          บ
echo                         บ        type 'cd\maydaysq'          บ
echo                         บ         and type 'HDGAME'          บ
echo                         ศออออออออออออออออออออออออออออออออออออผ


