@echo off
@cls
@echo      ออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
@echo ÿ
@echo                                Catch, If You Can
@echo                           Registration Form Print Out
@echo ÿ
@echo         You may fill in the form with a text editor first if you wish, and
@echo                                then print it out.
@echo ÿ
@echo                    Thank you for taking the time to register!
@echo ÿ
@echo              Press any key to print order form.  Ctrl-C will abort.
@echo ÿ
@echo      ออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
@pause >nul
@type order.frm >prn
