@echo off
cls
echo	ÿ
echo	                ________________________________________
echo	ÿ    
echo	                              BASS CHAMP      
echo	ÿ
echo                    Copyright 1991 by Shadowfax Software, Inc.
echo ÿ
echo	                        Floppy-Disk Installation
echo	                ________________________________________
echo	ÿ
echo	ÿ
echo Welcome!  Bass Champ's floppy disk installation has been simplified.
echo To create a fishing disk for running Bass Champ, use the DISKCOPY
echo command to dupilcate the program master disk.  Please run Bass Champ
echo from the duplicate and put the master away safely as a back-up.
echoÿ
echo For your convenience, Bass Champ uses no copy protection of any kind.
echo Thanks for respecting the copyright!
echo ÿ
echo For further information on the program, which may not be included in
echo the User's Manual...
pause
echo ÿ
type readme.doc
