
REM
REM Your batch file to execute Global War should look like this.
REM be sure and modify the subdirectory names to match your setup.
REM
REM First change to your Global War subdirectory
REM

CD\BBS\GWAR

REM Select one of the following depending on your BBS software

REM WAR /p \bbs\pcboard.sys
REM WAR /r \bbs\dorinfo1.def
REM WAR /w \bbs\chain.txt
REM WAR /i \bbs\callinfo.bbs
REM WAR /g \bbs\callinfo.bbs
REM WAR /d \bbs\door.sys
REM WAR /s \bbs\sfdoors.dat
REM WAR /c (baud) (port) (minutesleft) (firstname) (lastname)

REM Exit back to the BBS

CD\BBS

