@echo off

REM /d1 = debug mode (if enabled in distribution. Also required to bypass CD check)
REM /n  = do not play intro
REM /v? = display list of 2D video cards supported in native mode
REM /v1 = play it safe and use VESA mode
REM /vn = use specific 2D video card where n=card num displayed in /v?
REM       use /v1 for VESA mode if card not supported directly
REM /g  = run 3DFX Glide version (v1.07C or higher)

bc3000ad
