@echo off
cls
echo Thank you for purchasing Inherit the Earth CD-ROM!
echo 
echo We hope you'll have as much fun playing it as we did making it.
echo 
echo For those of you with Gravis UltraSound cards, make sure that you
echo run the GRAVIS.BAT file before running ITE.EXE or no sound will play.
echo 
echo 
echo Once again... Thanks and Enjoy.
echo 
echo 
echo        New World Computing, Inc.
echo                  and
echo           The Dreamers Guild
echo 
echo 

