echo off
cls
echo ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
echo บ       McMurphy's Mansion Version 1.6 (c) 1984, 1987, 1989   Martin-Art      บ
echo บ     P.O. Box 7493, Pasadena, TX 77508 USA  ALL RIGHTS RESERVED WORLDWIDE    บ
echo วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
echo บ McMurphy's Mansion is an all text adventure game that provides many hours   บ
echo บ of challenge and fun for everyone who plays. Your demented Uncle McMurphy   บ
echo บ has left you a $10,000,000 inheritance. ALL you have to do is find it!!     บ
echo บ Read the manual. This game is INTERESTING!  DIFFICULTY LEVEL:5  TIME:80 hrs บ
echo วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
echo บ SHAREWARE - This game is a shareware product.  If you enjoy playing, you    บ
echo บ should send $16.00 to the address shown below. If you play the game to its  บ
echo บ conclusion, it will average about 20 cents an hour!  You will receive a hintบ
echo บ sheet and game solution (on request) when you register.  Only registered    บ
echo บ players will receive them.  $2.50 of each registration is donated to a food บ
echo บ bank to feed the hungry. We have food. We should see that everyone does.    บ
echo บ PLAYING - Enter MCMURPHY at the DOS prompt and answer a few questions, then บ
echo บ enter MANUAL as a game command and the game mcmanual will print for you.    บ
echo วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
echo บ Shareware Address:     David Martin        ณ I hope you enjoy the Mansion!  บ
echo บ (For registrations     P.O. Box 7493       ณ Please register your software. บ
echo บ   and solutions)       Pasadena, TX 77508  ณ     David Martin, Author       บ
echo ศออออออออออออออออออออออออออออออออออออออออออออฯออออออออออออออออออออออออออออออออผ
rem pause
cls
echo Your adventure will be ready in a moment...
echo McMurphy's Mansion (c) 1984, 1987, 1989
echo Martin-Art
echo P.O. Box 7493, Pasadena TX,  77508
echo Please register your shareware today: Only $16.00
echo $2.50 goes to help feed the hungry.                    
echo Thanks,  David Martin, Author
mcmurphy

