@ECHO OFF
INTRO
IF NOT ERRORLEVEL 5 GOTO END
:MAIN_LOOP
KICK
IF ERRORLEVEL 5 GOTO END
MAIN
IF NOT ERRORLEVEL 0 GOTO EXIT
goto MAIN_LOOP
:EXIT
IF ERRORLEVEL 0 GOTO END
ECHO Please place keydisk in drive A or B
ECHO and restart
:END
