echo off
cls
echo:          ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออป
echo           บ This will print the Video BlakJak Instruction Manual. บ
echo           บ Make sure your printer is on line and put the print   บ
echo           บ head at the top of a page. You will need 60 pages.    บ
echo           บ If you don't want to print the manual now, just       บ
echo           บ hold down the CTRL key and tap the letter "C".        บ
echo           บ To go ahead with the printout, strike any other key.  บ
echo           ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
pause > nul
cls
echo:
echo:
echo                    Printing the Video BlakJak Manual Now!
copy vbj.doc prn
cls
echo:
echo                             Printout Complete!
prompt $p$g
