@echo off
cls
echo.
echo.
echo     *************************************
echo     *      TRANSPORT TYCOON DELUXE      *
echo     *              - CD -               *
echo     *************************************
echo.
echo *** Type ENGLISH and press enter to start the English Installation.
echo.
echo *** Entrez FRANCAIS et ENTRER pour commencer l'installation franáaise.
echo.
echo *** Bitte DEUTSCH tippen und die Enter-Taste drÅcken um das Deutsche 
echo     Installationsprogramm zu beginnen.
echo.
echo *** Escribe ESPANOL para comenzar la instalaci¢n en Castellano.
echo.
echo.
echo.
