ECHO OFF
CLS
ECHO ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ECHO ORDER FORM PRINT UTILITY
ECHO ßßßßßßßßßßßßßßßßßßßßßßßß
ECHO 
If you do NOT have a printer, please press Ctrl-C.

PAUSE
ECHO .>PRN
ECHO .>PRN
ECHO AMERICAN ORDERS MAIL TO:>PRN
ECHO Pinnacle Software, Box 714 Airport Road, Swanton Vermont, 05488>PRN
ECHO .>PRN
ECHO CANADIAN ORDERS MAIL TO:>PRN
ECHO Pinnacle Software, CP 386 Mont Royal H3P 3C6>PRN
ECHO .>PRN
ECHO INTERNATIONAL ORDERS MAIL $15 U.S. FUNDS TO:>PRN
ECHO Pinnacle Software, 1250 Laird 1A, Montreal, Canada, H3P 2T2>PRN
ECHO .>PRN
ECHO .>PRN
ECHO NOTE:  Do not mail cash.  Please allow 2 weeks for our bank to clear>PRN
ECHO        your cheque.  If you require top priority service, enclose a>PRN
ECHO        certified cheque or postal money order for same-day processing.>PRN
ECHO .>PRN
ECHO NOTE:  If you require 3.5 inch diskettes, check here ( ) and add three>PRN
ECHO        dollars to the usual $15 price.>PRN
ECHO .>PRN
ECHO .>PRN
ECHO .>PRN
ECHO .>PRN
ECHO DATE:  ________________________>PRN
ECHO .>PRN
ECHO .>PRN
ECHO .>PRN
ECHO Dear Pinnacle,>PRN
ECHO .>PRN
ECHO .>PRN
ECHO YES!  Rush me your grab-bag of quality shareware and public domain>PRN
ECHO programs!>PRN
ECHO .>PRN
ECHO .>PRN
ECHO My address is:>PRN
ECHO .>PRN
ECHO ______________________________________________________________________>PRN
ECHO .>PRN
ECHO ______________________________________________________________________>PRN
ECHO .>PRN
ECHO ______________________________________________________________________>PRN
ECHO .>PRN
ECHO ______________________________________________________________________>PRN
ECHO .>PRN
ECHO ______________________________________________________________________>PRN
ECHO .>PRN
ECHO .>PRN
ECHO I understand that I may use this software for six weeks, and if I am>PRN
ECHO not fully satisfied, I can simply return the diskettes and you will>PRN
ECHO cheerfully provide me with a full refund.>PRN
ECHO .>PRN
ECHO .>PRN
ECHO Signed,>PRN
ECHO .>PRN
ECHO .>PRN
ECHO ________________________________________>PRN
ECHO .>PRN
ECHO .>PRN
