@ECHO OFF
CLS
TYPE REGISTER.TXT
pause
cls
echo 
echo 
echo 
echo 
echo 
echo                             Puffwort's Evil Scheme 
echo 
echo 
echo 
echo          Copyright (c) 1995 Stephen D. Groll & Robert E. Rowell, 1995
echo                               All rights reserved.
echo            BRUN45.EXE (c) Copyright Microsoft Corporation, 1985-1988
echo              Portions GW (c) Copyright Crescent Software 1990-1991
echo 
echo 
echo 
echo 
echo 
echo 
echo 
echo 
echo 

