echo off
echo ÝNote: If you play world a lot it will need more than a 360k diskette. If you
echo Ýwish to register World, we have a 360k version that is split on 2 diskettes.
echo ÝOur toll-free order line is 800-VGA-GAME (1-800-842-4263).
echo Ý
echo ÝHere is your copy of Moraff's World, the Beginner's Version 7.0. Please play
echo Ý   and enjoy this game and please make copies for your friends. Shareware
echo Ý   games are supported by those who use and pay for them. Past support has
echo Ý   enabled the developement of our line of super high-res games.
echo Ý
echo ÝFeel free to distribute copies of this game in any of the following ways:
echo Ý   1) Placing the complete program on bulletin boards.
echo Ý   2) Making copies for friends.
echo Ý   3) Giving a free copy to paying customers.
echo Ý   4) Charging a nominal fee for the cost of the diskettes.
echo Ý
echo ÝType `MW' to start this game. This game allows only one character at a time.
echo Ý   To kill the existing character and start a new game, type `KILLCHAR'.
echo Ý   All instructions are built into this program's help files.
echo Ý
echo ÝCan you defeat the Shadow Dragon King on level 16?
echo Ý
echo ÝThe file UPLOAD.TXT contains one line and long descriptions of World for use
echo Ý   when uploading Moraff's World. Type UPLOAD to read it.
echo Ý                                                              Updated 5/25/93
