@echo off
cls
echo                  RING THOMPSON ENTERPRISES PRESENTS:
echo                            WRAITH BLASTER
echo                             Version 1.0
echo                            by Ken Dibble
echo         Created Using:  The BIG Adventure Game Toolkit 1.21
echo                  Copyright 1990  All Rights Reserved        
echo                  by David R. Malmberg & Mark J. Welch
echo                            Distributed by   
echo                               Softworks
echo                           43064 Via Moraga
echo                       Mission San Jose, CA 94539
RUNB WB
pause
cls
