echo ***    CANNOT FIND FILES...INSTALL NOT COMPLETE !      ***
echo   Please check MASTER GUIDE, fix problem, then try again.
echo        Check if INSTALL worked and files are loaded,
echo        or Check that MASTER and VOYAGE DISKS are 
echo        not damaged, and are in correct drives.
echo ***    CHECK INSTALLATION CONSIDERATIONS IN MANUAL !   ***
echo NOTE:   MOST installs work fine, and multiple intallations
echo often do not fix the problem... diagnose the problem FIRST.
