echo off
echo  Note- If you have downloaded this game from a PC bulletin board,
echo  you must have ALL 4 files: BANDOR-1.ZIP, BANDOR-2.ZIP, BANDOR-3.ZIP,
echo  and BANDOR-4.ZIP. The extension may vary (.ARJ, .LZH, etc.).
echo  Also, you do NOT need to run the Install.EXE program.  You do, however,
echo  need to do the following:
echo  Create a directory on your hard disk.
echo  Under that directory create two sub-directories, FMEM and MMEM
echo  Copy ALL files into the directory  you created.
echo  Copy ALL files that meet the wildcard F*.MEM to the sub-directory FMEM.
echo  Copy ALL files that meet the wildcard M*.MEM to the sub-directory MMEM.
echo  Delete ALL files that meet the wildcards F*.MEM and M*.MEM from the main
echo  directory.
echo  ÿ
echo  At the DOS prompt, regardless of where you received the game, you MUST
echo  run the CONFIG.EXE program to setup your sound and directory settings.
echo  If you have a SoundBlaster card and are going to use that option, BE SURE
echo  TO READ the bulletins concerning sound installation in the on-line manual.
echo  You may access the on-line manual at the DOS prompt by typing README.
pause 
echo  "Happy gaming!"
echo on