ECHO OFF
CLS
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
ECHO We are going to print the documentation file. Make sure your printer is on
ECHO and that it is loaded with plenty of paper.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo                Printing in progress . . . .
TYPE RANADIN.DOC >PRN
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo                . . . . Finished printing.
echo on
