echo off
echo ÝMoraff's Monster Memory, version 1.1                          UPDATED 9/25/92
echo Ý
echo ÝPlease enjoy this game and MAKE copies for your friends. Shareware programs
echo Ý    are supported by those who use and pay for them. Past support has enabled
echo Ý    the developement of this game and our complete line of multi-resolution
echo Ý    games which now support 1024x768.
echo Ý
echo ÝRegistered owners receive the advanced version of this game, and can obtain
echo Ý    Moraff's World and other exciting games as well!
echo Ý
echo ÝFeel free to distribute copies of this game in any of the following ways:
echo Ý    1) Placing complete program on bulletin boards (Please call it '!MONSTER')
echo Ý    2) Making copies for friends.
echo Ý    3) Giving a free copy to paying customers.
echo Ý    4) Charging a nominal fee for the cost of the diskettes.
echo Ý
echo ÝType 'MEMORY' to start this game.
echo Ý
echo ÝAll instructions are built into this program's help files.
echo ÝOur toll-free order line is 800-VGA-GAME (842-4263) or (512) 335-6399.
echo Ý
echo ÝWhen you upload Moraff's Monster memory, the BBS will ask you for a
echo Ý   description of this program. The file UPLOAD.TXT contains our recommended
echo Ý   one-line and extended descriptions.
