cls
echo off
echo *                                          *
echo *                                          *
echo NNN  N    OOO    TTT   III   CCCC      EEEEE
echo N N  N    O O     T     I    C         E
echo N  N N    O O     T     I    C         EEEE
echo N  N N    O O     T     I    C         E
echo N  NNN    OOO     T    III   CCCC      EEEEE
echo *                                          *
echo *                                          * 
echo REGISTRATION INFORMATION IS NOW COMPLETELY INCORRECT
echo *                                          *
echo FOR DONATION INFORMATION E-MAIL ARIES@KAGI.COM
echo *                                          *
echo THANK YOU.
echo on
pause
shape.exe


