:menu
echo off
cls
echo        зд© б б зд© зд© б   б б     дбд б б зд©     зд© б   зд© б б з©з
echo        Ё   цд╢ цд╢ цбы Ё   юбы      Ё  цд╢ цд      Ё   Ё   Ё Ё ЁЁЁ ЁЁЁ
echo        юдд а а а а аю  юдд  а       а  а а юдд     юдд юдд юды юаы аюы
echo ддддддддддддддддддддддд Copyright 1996 by Schenk & Horn ддддддддддддддддддддддд
echo.
echo.
echo     If you have problems with             Wenn Sie Probleme mit
echo     Charly the clown, you can             Charly the clown haben, k■nnen
echo     contact us:                           Sie uns wie folgt erreichen:
echo.
echo                     Internet..: frank_horn@formelbox.com
echo                     msn.......: Frank_Horn
echo                     AOL.......: FrankHorn
echo                     Compuserve: 75337,2752
echo                     Fido......: 2:240/4005.48
echo.
echo                     Mail....: Schenk & Horn
echo                               Kutterweg 8
echo                               D-23558 L│beck
echo                               Germany
echo.
pause
:cis
cls
echo        зд© б б зд© зд© б   б б     дбд б б зд©     зд© б   зд© б б з©з
echo        Ё   цд╢ цд╢ цбы Ё   юбы      Ё  цд╢ цд      Ё   Ё   Ё Ё ЁЁЁ ЁЁЁ
echo        юдд а а а а аю  юдд  а       а  а а юдд     юдд юдд юды юаы аюы
echo ддддддддддддддддддддддд Copyright 1996 by Schenk & Horn ддддддддддддддддддддддд
echo.
echo.
echo.
echo     If your computer hangs up while      Wenn Ihr Computer beim Start
echo     starting the program and the         des Spieles abst│rzt und Sie
echo     program is correctly installed       das Spiel korrekt mit SETUP.EXE
echo     by using the SETUP.EXE, please       konfiguriert haben, probieren
echo     try the following:                   Sie folgende Aufrufe:
echo.
echo.
echo.
echo                        -  START nosound
echo                        -  CLOWN    
echo                        -  CLOWN nosound
echo.
echo.
echo.
pause
cls
