@echo off
cls
@echo ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ        Loading this installation program will take a few moments. . .       บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo บ                                                                             บ
@echo ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
@echo off                                                                           
ins                                                                                
                                                                                    
                                                                                    
