cls
@echo off
@echo ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
@echo บ Note:                                                      บ       
@echo บ   MOONGRAV is only for Gravis Ultrasound sound cards.      บ
@echo บ   If you do not have a Gravis Ultrasound in your computer  บ
@echo บ   you should start the game by typing "MOON".              บ
@echo ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
@echo Press CTRL+C to exit or
@pause
@echo ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
@echo บ   -- Uploading MIDI patches for Under a Killing Moon. --   บ
@echo ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
loadpats 
TEX3 %1 %2 %3 %4 %5

