echo off
cls
echo ELFLAND: The Troll Caves - Volume Two
echo       Thank you for ordering! This disk is NOT SHAREWARE! Do not 
echo   distribute this disk, or any portions of it, under any circumstances.
echo CHEAT MODE AND HINTS!
echo       From the command line, type 'VIEW HINTS2' to view the hints and
echo   the information on how to enter the secret cheat mode. If you would
echo   like a hard copy of this information, print out the file 'HINTS2'
echo   included on this disk.
echo OPTIONAL
echo       Supports joystick control and Soundblaster card (make sure the
echo   file CT-VOICE.DRV, supplied with your Soundblaster, is either in your 
echo   Soundblaster drivers directory or Elfland directory).
echo INSTALLATION
echo       There is no special installation procedure. Just copy all the
echo   files on this disk to the desired hard drive or disk that exceeds 360k.
echo START
echo       From the command line, type 'ELF2' to start Elfland. Good luck!

