@ECHO OFF
CLS
TYPE EXAMP.BDT
ECHO.
PAUSE
cls
ECHO.
ECHO.
ECHO.
ECHO.
ECHO    If you find any problems, or have any comments or suggestions,
ECHO    please feel free to contact Awesome Softworx by MODEM.
ECHO.
ECHO    Our 24hr BBS service number is (818)701-7465.  Please report
ECHO    any problems concerning our BBS to 
ECHO                   4157 W 5th Str Suite 222
ECHO                   Los Angeles, CA 90020
ECHO.
ECHO.
ECHO.
ECHO    You can type "Q2PLUS /T" to skip this message next time.
ECHO.
ECHO.
PAUSE
Q2PLUS %1 %2
ECHO.
