echo off
cls
echo 05 Oct 1988 - New features and/or changes to ECHELON Space Simulator
echo (c) 1988 ACCESS Software, Inc. V1.00
echo .
echo TIME/DATE
echo	 In order to acheive its precise timing control, the ECHELON program
echo	 alters the timing system of the computer. To avoid problems with time
echo	 and date functions, the current time and date are preserved and re-
echo	 stored when the program is terminated. This means that the time and
echo	 date will be exactly the same when the program is finished as it was
echo	 when the program is started.
echo	.
