@ECHO OFF
FORMAT A: /S
COPY CONFIG.JMO A:\CONFIG.SYS
COPY AUTOEXEC.JMO A:\AUTOEXEC.BAT
ECHO.
ECHO Note: You must supply your own lines for loading your CD-ROM drivers in the
ECHO places indicated in A:\CONFIG.SYS and A:\AUTOEXEC.BAT.
ECHO.
ECHO Then whenever you want to play CyberRace, put the boot disk into your A drive
ECHO and boot your computer. (Booting your computer means turning it on, or
ECHO pressing the reset button, or pressing Ctrl-Alt-Delete.) After playing
ECHO CyberRace, you can return your computer to normal by removing the boot disk
ECHO and rebooting your computer.
ECHO.
