echo off
cls
echo so wait a while...

echo i have to clean up the dungeon...

copy level1.maz %11.maz > nul:
echo won't be a minute...

copy level1.obs %11.obs > nul:
echo what a pain...

copy level2.maz %12.maz > nul:
echo busy, busy, busy...

copy level2.obs %12.obs > nul:
echo the last one of you adventurers left such a mess...

copy level3.maz %13.maz > nul:
echo tsk, tsk...

copy level3.obs %13.obs > nul:
echo all right.  that's it.

echo away with you!

echo (press 'h' for a little help!)

