REM (C) TOPO Soft 1992
ECHO OFF
CLS
ECHO                  +----------------------------------+
ECHO                  ›     OLIMPIADAS 92 -Atletismo     ›
ECHO                  +----------------------------------+
echo .
ECHO                         -Informaci¢n adicional-
echo El funcionamiento de este programa ha sido verificado en varios ordenadores,
echo obteniÇndose en todos los casos una compatibilidad 100x100.
echo Aun as°, y dada la gran variedad de modelos PC existentes en el mercado,
echo con toda su amplia gama de configuraciones, pudiera darse el caso de problemas
echo en la instalaci¢n y/o la ejecuci¢n.
echo .
echo Dado que todos los ficheros que componen el programa se encuentran comprimidos
echo no se puede ejecutar este programa sobre los discos suministrados, previamente
echo tendr† que instalarlos en su DISCO DURO.
echo Para una f†cil instalaci¢n del programa se le suministra la utilidad 
echo INSTALAR contenida en el disco 1.
echo Por favor, aseg£rese de seguir al pie de la letra todas las indicaciones
echo dadas por INSTALAR.
echo Este programa ocupa 8 Megas.
echo Aseg£rese de que al hacer un directorio de su DISCO DURO este le de como
echo espacio libre un valor mayor que 8,100.000 bytes free (espacio disponible).
ECHO .
pause

cls
ECHO               -Soluciones a los posibles errores de instalaci¢n-
echo .
echo -Si en la instalaci¢n obtuvo un error por falta de memoria act£e en
echo  consecuencia. Existen diferentes utilidades de compresi¢n de datos  
echo  de dominio publico (P.ej. LHa, ARJ, etc.) con las cuales conseguir† ahorrar
echo  espacio en su disco duro, comprimiendo ficheros y directorios poco utilizados 
echo  con la opci¢n de descomprimirlos en cualquier momento.
echo .
echo -Si en la ejecuci¢n del juego obtuvo error por falta de memoria del sistema
echo  es posible que los drivers que tenga instalados en su arranque (config.sys o
echo  Autoexec.bat) estÇn recortando bastante la memoria libre del sistema.
echo  para solucionarlo no le aconsejamos que los anule, puesto que pueden ser
echo  imprescindibles para el correcto funcionamiento de otros programas.
echo  Lo que tiene que hacer, no solo para OLIMPIADAS 92, sino para cualquier otro
echo  programa que le de fallos por falta de memoria del sistema,
echo  es crearse un disco de arranque, solo con el driver del rat¢n.
echo  Otra soluci¢n es adquirir la nueva versi¢n de MS DOS (5.0) con la que se
echo  obtiene un aumento considerable de la memoria del sistema. Utilizando los
echo  comandos DOS=HIGH, DEVICE HIGH=driver..., etc.
ECHO .
pause
cls
echo -El juego funciona con rat¢n MICROSOFT o compatible, pero podr°a darse
echo  el caso de alg£n tipo de incompatibilidad con un determinado modelo de rat¢n,
echo  por no adaptarse este a las especificaciones de compatibilidad,
echo  o por una mala configuraci¢n del mismo. En cualquier caso puede utilizar el
echo  teclado especificado en el manual de instrucciones.
echo .
echo -Si al instalar el programa obtiene como resultado repetidos errores de 
echo  lectura (Read error), le rogamos acuda al establecimiento donde adquiri¢
echo  el juego, all° le solucionaran el problema.
echo .
echo -Para agilizar el acceso a disco duro te aconsejamos que utilices  un driver 
echo  cachÇ o el SMARTDriver incluido tanto en MS-DOS 5.0 como en WINDOWS.
ECHO .
pause
CLS
ECHO                   +----------------------------------+
ECHO                   ›     OLIMPIADAS 92 -Atletismo     ›
ECHO                   +----------------------------------+
echo .
echo                               -CRêDITOS-
echo .
echo                     PROGRAMA:           David Lopez
echo                                         Javier Fafula
ECHO                     IDEA:               Rafa G¢mez
echo                                         David Lopez
echo                                         Javier Fafula
ECHO                     ANIMACI‡N:          Jorge Azpiri
echo                     FONDOS:             -ACE-
echo                     RENDERING:          -ACE-
ECHO                     MÈSICA:             BIG TOXIC
echo                     EFECTOS DE SONIDO:  BIG TOXIC
ECHO                     PRODUCCI‡N:         Rafa G¢mez
ECHO .
ECHO                              Topo Soft 1992
echo .

