@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo Redneck Rampage Cuss Pack Uninstaller
@echo -------------------------------------
@echo.
@echo So you're sick of the mindless repetition of base profanity?
@echo.
@echo Press any key to delete the Redneck Rampage Cuss Pack.  This will
@echo return Redneck Rampage to its original pristine state.
@echo.
@echo Press CTRL-C to exit to DOS and leave the Cuss Pack intact.
@echo.
@echo off
pause
@echo on
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo OK, the Cuss Pack is going to be deleted.  After all the sound files
@echo are deleted, don't forget to change your .RTS file full of multiplayer
@echo taunts back to the REDNECK.RTS file.  To do this, run the SETUP
@echo program, choose 'Sound Setup', choose 'RTS File Selection', choose
@echo 'Choose RTS File', and then choose REDNECK.RTS.
@echo.
@echo Got that?  Hit ENTER to delete the Cuss Pack once and for all.
@echo.
@echo off
pause
del *.voc
del cusspack.rts
del coot.con
del readme.txt
rename oldcoot.con coot.con
@echo on
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo Cuss Pack deleted!  
@echo.
@echo off
pause

