@echo off
cls
echo MONDAY NIGHT FOOTBALL HARD DRIVE C INSTALLATION
echo INSERT CAMERA 1
pause
md c:\monday
copy *.* c:\monday
echo INSERT CAMERA 2
pause
copy *.* c:\monday
echo INSERT CAMERA 3
pause
copy *.* c:\monday
echo INSERT CAMERA 4
pause
copy *.* c:\monday
echo INSERT CAMERA 5
pause
copy *.* c:\monday
echo INSERT CAMERA 6
pause
copy *.* c:\monday
cls
echo MONDAY NIGHT FOOTBALL HARD DRIVE INSTALLATION COMPLETE
echo TYPE "MONDAY<RETURN>"
echo Copied 138 files
echo Get ready to be blown away...
c:
cd \monday
@echo on
