cls
echo off
echo    ****************************************************
echo    *                                                  *
echo    *               Spectrum Holobyte                  *
echo    *                                                  *
echo    *            Score Clearing Program                *
echo    *                                                  *
echo    *               Copyright 1989                     *
echo    *                                                  *
echo    ****************************************************
copy score.bak score.bin
echo on
