ECHO OFF
CLS
ECHO   ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO   บ  Vegas Pro Video Poker  (C) 1989 WorkWare Co.  All Rights Reserved บ
ECHO   บ  The following is a complete list of disk files for the program:   บ
ECHO   บ                                                                    บ
ECHO   บ  VEGASPRO.EXE:  The executable program, the game itself.  Type in  บ
ECHO   บ                 "VEGASPRO" at the DOS prompt and press Enter.      บ
ECHO   บ  VEGASPRO.HLP:  Instructions on how to use the program.  Read the  บ
ECHO   บ                 file during the game by pressing 'F1' for help.    บ
ECHO   บ  VEGASPRO.INF:  Information about other poker games:  read the     บ
ECHO   บ                 file by pressing 'R' at the game's Main Menu.      บ
ECHO   บ  README.EXE:    An executable program that reads the help file     บ
ECHO   บ                 "vegaspro.hlp" without starting the game.  Type    บ
ECHO   บ                 in "README" at the DOS prompt and press Enter.     บ
ECHO   บ  VEGASPRO.PKR:  A file created by the game to store your payoffs,  บ
ECHO   บ                 game state, etc.  It may or may not be present.    บ
ECHO   บ  TROUBLE.BAT:   Trouble-shooting help.  If you have trouble start- บ
ECHO   บ                 ing "vegaspro.exe" or "readme.exe," type "TROUBLE" บ
ECHO   บ                 and press Enter to read "trouble.bat".             บ
ECHO   บ  FILELIST.BAT:  This file.                                         บ
ECHO   บ                                                                    บ
ECHO   บ  WorkWare, 5130 E. Charleston, #5, L.V., NV 89122 (702) 641-4931   บ
ECHO   ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
