ECHO OFF
CLS
ECHO   ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO   บ  TROUBLE STARTING UP:  When VEGAS PRO VIDEO POKER (VEGASPRO.EXE)   บ
ECHO   บ  starts up, it assumes that your computer is IBM-compatible.  If   บ
ECHO   บ  when the program starts, it doesn't do anything, or "hangs" your  บ
ECHO   บ  computer, your computer isn't "compatible" enough.  You may still บ
ECHO   บ  be able to run the program, however, by starting it as follows:   บ
ECHO   บ                                                                    บ
ECHO   บ    1)  Enter "VEGASPRO -S".  Try this if the program "hanged"      บ
ECHO   บ        your computer or nothing showed on screen.  The "-S"        บ
ECHO   บ        command-line parameter prevents the program from writing    บ
ECHO   บ        directly to the screen RAM addresses.                       บ
ECHO   บ    2)  Enter "VEGASPRO -N".  Try this if the program started,      บ
ECHO   บ        you saw a sign-on screen, but nothing else happened when    บ
ECHO   บ        you pressed a key to go on.  The "-N" prevents the pro-     บ
ECHO   บ        gram from using sound effects.                              บ
ECHO   บ    3)  Enter "VEGASPRO -S -N".  This invokes #1 and #2.            บ
ECHO   บ                                                                    บ
ECHO   บ  The command-line parameters "-S" and "-N" work with the help-file บ
ECHO   บ  reader (README.EXE) too:  for example, enter "README -S".         บ
ECHO   ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
