@echo off
echo ÿFollowing rules are not addressed properly in the manual:
echo ÿ
echo ÿ- Paratroops may part in an assault up to 4 hexes away.
echo ÿ
echo ÿ- Desert hexes are handled exactly the same as clear hexes. Only the
echo ÿ  graphics differ. There is no defence bonus for desert.
echo ÿ
echo ÿ- Wood costs 1 AP to enter, gives no defence bonus for ground combat
echo ÿ  and shifts air strikes against this hex one column to the left.
echo ÿ
echo ÿ- Basic chance for an amphibious invasion is 70%, not 80% as stated in
echo ÿ  the rules. Basic chance is set to 40% if invading against a fort.
echo ÿ  In both cases basic chance will be halved if invading a city and/or
echo ÿ  invading an occupied tile. Artificial harbors invading an 
echo ÿ  unoccupied non city hex will always have 70% chance for success.
echo ÿ  There may be up to two tests against the modified invasion chance.
echo ÿ  If first passes unit will land in fine order. If first passes and
echo ÿ  second fails, unit will take losses and be set to 0 AP. If both fail
echo ÿ  unit becomes dissolved.
echo ÿ
echo ÿ- The interception range is 4 hexes, not 7 as stated. Also there is a
echo ÿ  further 50% that an available unit will not intercept. You get the
echo ÿ  column on the interception combat table by substracting the 
pause
echo ÿ  interceptors effective strength from the bombers effective strength 
echo ÿ  and rounding towards 0. So -1.4 would be resolved on the -1 column 
echo ÿ  and 1.4 on the +1 column. The combat table is symetrical, so no 
echo ÿ  advantage for either bomber or interceptor.
echo ÿ
echo ÿ- If a hex in a non-clear weatherzone is attacked, then the effective
echo ÿ  strength of the bomber is divided by 3 for calculating the column on
echo ÿ  the ground strike table.
echo ÿ
echo ÿ- The strenght of Malta garrison has been improved.
echo ÿ
echo ÿ- Effects of Blitzkrieg have been changed. Now Blitzkrieg lasts until
echo ÿ  end of the turn and each impulse Allied units north-east of Paris 
echo ÿ  may get reduced morale.
echo ÿÿÿ