@ECHO Now installing SPISEDIT! (Spispopd v3.0)
@ECHO The game of the century
@ECHO (Or at least of the week)
@ECHO I hope you're running this from your SPISPOPD directory,
@ECHO because otherwise, it'll like put stuff all over the place.
@PAUSE
@ECHO Making a VOC directory!
@MD VOC
@ECHO Unpacking digitally packaged sound effect modules.
@PKUNZIP SPISVOC.ZIP VOC
@DEL SPISVOC.ZIP
@ECHO ÿ
@ECHO Unpacking highly complex cool data informational packets.
@PKUNZIP SPISED.ZIP
@DEL SPISED.ZIP
@ECHO ÿ
@ECHO GROOVY!  It's done!
@ECHO Now type "SMASH" to play the coolest game you've seen in a
@ECHO long while...
@ECHO ÿ
