cls
@echo off
@echo - PC Brutal Sports' controls:
@echo -
@echo - 	During the TITLESCREENS, you will be presented
@echo - 	with options requiring input.
@echo - 	Default keys are;
@echo -  	left	-	{lft curs},'I'
@echo -  	right	-	{rgt curs},'O'
@echo -  	up	-	{up  curs},'W'
@echo -  	down	-	{dwn curs},'S'
@echo - 	fire '1'- 	{space}   ,'1'	
@echo - 	fire '2'- 	{return}  ,'2'
@echo - 
@echo - On joysticks, Fire3 can be found by using Fire1 and Fire2
@echo - at the same time.
@echo - If you are using a fast PC, you may alter the speed of play
@echo - by using the function keys F1 - F8
@echo off
pause
new.exe
cls



