@echo off
cls
cd drivers
echo Iron Cross utilizes the best sound technologies
echo available. Whenever you combine the best in Sound
echo and Music you inevitably have problems. The Gravis
echo UltraSound card is a wonderful card, but due to a
echo conflict, not solved before we shipped, you can only
echo play Iron Cross on the UltraSound if you select Sound
echo or Music, not both. To do this run the INSTALL program
echo and select UltraSound for Sound and NONE for Music or
echo vice-versa. Although Iron Cross has great music we   
echo feel that you will get more enjoyment from the Sound  
echo and Sound Effects.
echo 
echo You only need to run GRAVIS.BAT if you are playing
echo Iron Cross with Gravis UltraSound selected for Music.
loadpats
cd..
