echo off
cls
echo         ллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллл
echo         лл                                                         лл
echo         лл             JIMMY WHITE'S WHIRLWIND SNOOKER             лл
echo         лл                                                         лл
echo         лл                 (/) 1992 TRSI                           лл
echo         лл                                                         лл
echo         ллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллл
echo џ
echo џ
echo џ
echo џ
START.COM
echo џ
echo Thank you for playing Jimmy White's Whirlwind Snooker
echo џ

