echo off
echo ÝUpdated 2/13/94
echo Ý
echo ÝThank for supporting MoraffWare.
echo Ý
echo ÝThis is Moraff's Morejongg, Advanced Version 3.0, copyright, 1994.
echo Ý
echo ÝStart it by typing 'MOREJONG'.
echo Ý
echo Ý
echo ÝNote that Morejongg saves each game. That means that you may need a good deal
echo Ý   of disk space, if you play it a lot. Each game takes about 3k, so 300
echo Ý   different games would require about a meg. Saved games are all saved as
echo Ý   '*.smj'. To delete all of the previously played games, just type
echo Ý   'DEL *.SMJ' at the DOS prompt. Or delete individual games by typing, for
echo Ý   example, 'DEL 1001.SMJ'.
echo Ý
echo ÝThank you for your support and please enjoy this game!
echo Ý
echo Ý
echo Ý
echo Ý
echo Ý

