ECHO OFF
CLS
ECHO.
ECHO.               WELCOME TO CONRAD BUTTON'S TEXT ADVENTURE SERIES
ECHO.
ECHO.   HOW TO START YOUR ADVENTURE
ECHO.
ECHO.       1. Be sure the game disk is in drive A
ECHO.       2. Type A: and press Enter
ECHO.       3. Type ASIA for THE ASIAN CHALLENGE
ECHO.          type SAMERICA for SOUTH AMERICAN TREK
ECHO.          type AFRICA for AFRICAN SAFARI
ECHO.          type CASTAWAY for CASTAWAY
ECHO.          type NEBULA for NEBULA
ECHO.          type DARKCON for DARK CONTINENT
ECHO.          type REDPLAN for RED PLANET
ECHO.          type TIMETRAV for TIME TRAVELER
ECHO.          type AGENT for SPECIAL AGENT
ECHO.          type SANC for SANCTUARY
ECHO.          type RAIDERS for RAIDERS OF THE STAR TEMPLE
ECHO.          type RUBICON for AVENGER OF RUBICON
ECHO.       4. Press Enter
ECHO.
pause
ECHO.
ECHO.     If you are using a graphics monitor that only displays
ECHO.     one color you should use the M parameter when starting
ECHO.     the games  (i.e.  ASIA M).
ECHO.
ECHO.   The file README.DOC contains an introduction to Button's
ECHO.   Adventure Series and helpful suggestions for playing text
ECHO.   adventures.  To view this file on your screen, type
ECHO.             "MORE < A:README.DOC"    [ Do not include the " " ]
ECHO.   To obtain a hardcopy, turn on your printer and then type
ECHO.             "COPY A:README.DOC PRN"
ECHO.
ECHO.
