echo off
cls
echo                   SILPHEED ADDITIONAL DOCUMENTATION
echo                             MAY 7,1990
echo.
echo.
echo - MUSIC VOLUME CONTROL.
echo. 
echo         Music volume may be changed from the keyboard for those music cards
echo         which support volume control.
echo. 
echo                 To INCREASE Volume - Press and hold the key that is two 
echo                                      keys to the left of the "<- BACKSPACE"
echo                                      key. (This is the "+" and "=" key
echo                                      for the US keyboard.) 
echo. 
echo                 To DECREASE Volume - Press and hold the key that is three 
echo                                      keys to the left of the "<- BACKSPACE"
echo                                      key. (This is the "-" and "_" key
echo                                      for the US keyboard.) 
echo.
echo.
pause
                        
