CLS
@ECHO OFF
ECHO =============================================================================
ECHO INSTALACION KOME BUMB				   JUEGOS PARA TU PC No. 3
ECHO =============================================================================
ECHO.
ECHO.
ECHO Instalando, espere por favor.
MD C:\CBOOM > NUL
XCOPY a: c:\cboom /s > NUL
C:
CD\
CD C:\cboom > NUL
cls
echo Para jugar , teclea CBOOM y despu‚s pulsa ENTER.



