echo.
echo :                  Gravis UltraSound                      :
echo :                                                         :
echo :   The UltraSound card requires the ULTRAMID program     :
echo : to be loaded into memory. This may use up valuable base :
echo : memory. You may wish to use a memory management utility :
echo :        to load ULTRAMID.EXE into upper memory.          :
echo :                                                         :
echo :    To prevent this message being repeatedly shown,      :
echo :            enter the command STOPMESS                   :
echo.
cls