echo off
cls
echo The procedure for installation has changed since the manual
echo went to press.  To install Conquest of Japan, type
echo - 
echo                       INSTALxy
echo -
echo where x is the drive you are copying from, and y is the drive
echo you are copying to.  You can install this game from drives A
echo or B, to drives C, D or E.  To install Conquest of Japan on some
echo higher hard drive, make a directory \CONQUEST for them and copy
echo the files to them.  The six valid Install programs are:  
echo                        INSTALAC
echo                        INSTALBC
echo                        INSTALAD
echo                        INSTALBD
echo                        INSTALAE
echo                        INSTALBE
echo Thank you.
echo on

