set SST_GRXCLK=90
set SST_FT_CLK_DEL=0x4
set SST_TF0_CLK_DEL=0x6
set SST_TF1_CLK_DEL=0x6
set SST_VIN_CLKDEL=0x1
set sst_SLIDETECT=0
SET FX_GLIDE_SWAPINTERVAL=1
set SST_VOUT_CLKDEL=0x0
set SST_TMUMEM_SIZE=2
SET SSTV2_FASTMEM=1
SET SSTV2_FASTPCIRD=1
SET FX_GLIDE_ALLOC_COLOR=3
SET SST_SWAP_EN_WAIT_ON_VSYNC=1
cd fatdata
intro
cd ..
whip3dfx.exe /fx480
