ECHO OFF
ECHO This is a documentation file to assist
ECHO you in installing your PC JR.
ECHO -
ECHO If you have one of the three expansion
ECHO modules listed below you need only to
ECHO type the appropriate batch file name as
ECHO listed to install your Robot Odyssey
ECHO disk. If your expansion module is not
ECHO listed below, you may have to modify
ECHO one of the JR***INS.BAT files along
ECHO with its JR***CON.SYS file.
ECHO -
ECHO Enter the batch file command with your
ECHO Robot Odyssey disk mounted.


ECHO -
ECHO If IBM PC JR Expansion type B:JRIBMINS
ECHO If MicroSoft Expansion type B:JRMICINS
ECHO If TECMAR Expansion type B:JRTECINS
:END
