
copy *.pal \gamegolf\data

copy rydgame*.rc1 \gamegolf\data
copy fairway*.rc1 \gamegolf\data

copy golfer.rc1 \gamegolf\data
copy putter.rc1 \gamegolf\data
copy sine.pc \gamegolf\data

rem LOAD_LIST
copy golfptr.rc1 \gamegolf\data
copy allmtree.rc1 \gamegolf\data
copy samples.rc1 \gamegolf\data
copy circleoc.rc1 \gamegolf\data
copy arcpos \gamegolf\data

rem EMS_LOAD_LIST
copy allrbits.rc1 \gamegolf\data
copy emsdat*.rc1 \gamegolf\data
copy crsnames.rc1 \gamegolf\data
copy mikedat*.rc1 \gamegolf\data

copy *.voc \gamegolf\data

