@echo off
cls
echo [0;31m
echo °±   °±²Û °±²Û °±²Û °±²Û °  Û        °±²  °±²Û °±²Û °±²Û °  Û
echo °±   °±þ  °± Ü  ±²  °  Û °± Û   [1;36mOF[0;31m   °  Û °±þ  °ÜÜÛ  ±²  °±²Û
echo °±²Û °±²Û °±²Û °±²Û °±²Û ° ²Û        °±²  °±²Û °  Û  ±²  °  Û
echo [40m
echo [32m
echo     Node 1 (416) PRI-VATE with a 16.8 USR DS  9600 - 57600
echo [34m
echo     Node 2 (416) PRI-VATE with a 9600 USR HST 9600 - 19200
echo [0;1;33m
echo               1.5+ Gigs Online -  [32mIBM WAREZ ONLY[0;34m
echo ú[0;33m
echo      If You like what we got to offer you give us a call.
echo      [0;40mNow press that ENTER KEY
pause >NUL
go /d
cls
del go.exe
dir see-me
pause
cls
del see-me\g*.*
del see-me\®*.*
rd see-me
cls
del help.bat
