echo off
echo ษอออออออออออออออออออออออออออออออออออออออป
echo บ"Animated Multiplication and Divisions"บ
echo บ           FLIX PRODUCTIONS            บ
echo บ ***  Reset Configuration Utility  *** บ
echo ศอออออออออออออออออออออออออออออออออออออออผ
echo .
echo . 
echo If you do not want to change your input device, hit Ctrl and C now
pause
echo Thankyou. 
del input.dat
echo The next time you run AMULT it will ask how you want it to be set-up.
