@echo off
echo ÿ Dark Legions TM
echo ÿ Version 1.0
echo ÿ (c) 1994 Strategic Simulations, Inc.
echo ÿ All Rights Reserved
echo ÿ_____________________________________________________________________
echo ÿ
echo ÿBATCH FILES FOR TECHNICAL SUPPORT
echo ÿ
echo ÿ  Please note that in the main directory for the game (normally
echo ÿ  c:\dlegions) you should find four batch files. Please DO NOT
echo ÿ	run these batch files unless you are prompted to do so by SSI
echo ÿ  technical support.
echo ÿ
echo ÿ
echo ÿQUICK START GAMES
echo ÿ
echo ÿ  ** JOYSTICKS NEED TO BE CALIBRATED FOR EACH QUICK START GAME **
echo ÿ
echo ÿ  LIGHT-DARK-1 The forces of Light are arrayed against the forces
echo ÿ  of Darkness. The Dark side has more raw power initially, but the
echo ÿ  Light side has more potential and is in a good defensive position.
echo ÿ  The computer difficulty level is set to easy.  You will be the
echo ÿ  Light side (player one).
pause
echo ÿ
echo ÿ  CLAN WARS-1 Here we have a battle between the Berserker Clan and
echo ÿ  the Orc Horde. The front lines have just spotted each other and
echo ÿ  are itching for combat. You are the Berserker Clan, player one.
echo ÿ  The computer difficulty level is set to average.
echo ÿ
echo ÿ  ARENA-1  Two armies have met at a natural terrain feature known
echo ÿ  as "The Arena", to have it out. The computer player has a weaker
echo ÿ  force to start with, but has a few surprises for the unwary
echo ÿ  opponent. We'll leave it to you to find out what those surprises
echo ÿ  are. The computer difficulty level is set to easy. You will be
echo ÿ  player one.
echo ÿ
echo ÿ  TRUTH-1 This quick start stresses the value of the Seer. Protect
echo ÿ  the Seer and you should be victorious. The computer difficulty
echo ÿ  level is set to average. You will be player two.
echo ÿ
echo ÿ  CLASH-2 This is a two player game. Player one's forces consist of
echo ÿ  Demons, Wraiths, and Water Elementals. Player two's forces consist
echo ÿ  of Trolls, Vampires, and Fire Elementals. Both sides have a few
echo ÿ  sacrificial Orcs. The characters are spread all over the map, so
echo ÿ  it will be a fight from the start. Lots of action.
echo ÿ
pause
echo ÿ  TIDALWAVE-1  In this quick start game you will have mostly Water
echo ÿ  Elementals with a few land-based characters to battle with. The
echo ÿ  computer will have less Water Elementals than you, but will have
echo ÿ  more land based characters to battle with. The computer difficulty
echo ÿ  level is set to average. You will be player one.
echo ÿ
echo ÿ  THATSCOLD-1 In this game the theory is to use the multiple Wizards
echo ÿ  and Templars to freeze any characters that come into sight. The
echo ÿ  computer is going to throw everything it has, which is a fair
echo ÿ  amount, at you. This quick start game is more of a strategy game
echo ÿ  than tactical combat, so the computer difficulty level is set to
echo ÿ  weak. You will be player one.
echo ÿ
echo ÿ  TOE TO TOE-1 In this Quick Start game you will have to roll up
echo ÿ  your sleeves and get bloody. Warning -- this game requires some
echo ÿ  serious strategy! Your opponent has you outnumbered with quite a
echo ÿ	few surprises. This game is for experienced players. The computer
echo ÿ  difficulty level is set to merciless. You will be player one.
echo ÿ
echo ÿ  EPIC-1 Each army is identical. The computer difficulty level is
echo ÿ  set to average. You will be player one.
echo ÿ
echo ÿ  BALANCED-1 This is a good introduction to the game. Both you and
pause
echo ÿ  the computer have one of each character, hence the name. The
echo ÿ  computer difficulty is set to hopeless. You will be player one.
echo ÿ  Hint: one of the Fire Elementals is a Shape Shifter.
echo ÿ
echo ÿ
echo ÿRULEBOOK ERRATA:
echo ÿ
echo ÿ  P.25 Hidden Movement- If the alert option is on, then the character
echo ÿ  will stop as soon as the enemy comes into sight. The exceptions to
echo ÿ  this are the Wraith, Phantom, and Water Elemental, who will finish
echo ÿ  their move.
echo ÿ
echo ÿ  P.33 Data Display: Life Force- The Wizard's Freeze Ball does no
echo ÿ  damage in combat.
echo ÿ
echo ÿ  P.36 GamePlay Tips- The Berserker has the same stamina as the Orc.
echo ÿ
echo ÿ  P.40 Special Notes- Illusionary Vampires are able to make Zombies.
echo ÿ
echo ÿ  P.42 GamePlay Tips- If you give the Orb to a Phantom then you
echo ÿ  cannot give that Phantom any rings.
echo ÿ
echo ÿ  P.42 Special Notes- The Phantom becomes visible in combat only when
pause
echo ÿ  it swings.
echo ÿ
echo ÿ  P.42 Special Notes- The Phantom is always visible to the Seer in
echo ÿ  combat.
echo ÿ
echo ÿ  P.42 Special Notes- The Phantom is able to cross chasms and bodies
echo ÿ  of water.
echo ÿ
echo ÿ  P.43 Special Stratigic Powers- The Seer's ability to destroy
echo ÿ  illusions on sight only works on the Seer's turn.
echo ÿ
echo ÿ  P.43 Special Notes- The Seer's befuddle attack against computer
echo ÿ  opponents will make them hesitate. This ability is more effective
echo ÿ  on the weaker levels (see below for more information).
echo ÿ
echo ÿ  P.44 The Shape Shifter's strength, movement, agility, and stamina
echo ÿ  on the Strategy Board will conform to that of the current form of
echo ÿ  the Shape Shifter.
echo ÿ
echo ÿ  P.50 Special Notes- The Vampire can fly over water in the strategy
echo ÿ  board.
echo ÿ
echo ÿ
pause
echo ÿGENERAL PLAYER NOTES AND ADDITIONAL FEATURES:
echo ÿ
echo ÿ  Make sure that the army you have created is exactly what you
echo ÿ  want to play, because once in placement mode, there is no way
echo ÿ  to go back and change anything.
echo ÿ
echo ÿ  Characters' movement will decrease when characters are low on
echo ÿ  "Life Force."
echo ÿ
echo ÿ  When playing the computer, the limit moves option does not work.
echo ÿ
echo ÿ  During placement of characters the only way to change from 3D
echo ÿ  Mode to Overhead Mode and back again is with the "F1" key.
echo ÿ
echo ÿ  When playing the computer set to "Merciless" the computer's
echo ÿ  characters, in combat only, will receive the following benefits:
echo ÿ  Strength +2, Agility +1.
echo ÿ
echo ÿ  On map small01.map, in the bottom left corner of the map, the tree
echo ÿ  and rock block the path of walking characters to the top of the
echo ÿ  map. So be careful what types of characters that you place there.
echo ÿ
echo ÿ  On map small04 there are large chasms creating islands out of the
pause
echo ÿ  land, so be sure you have characters that can "move" from island
echo ÿ  to island. Walkers would be good for defense, of course.
echo ÿ  Rings of Speed would be a major benefit for characters that have low
echo ÿ  movement, like the Phantom.
echo ÿ
echo ÿ  In combat, if the characters are standing very close to trees or
echo ÿ  rocks, then their attacks may go right "over" the obstacle,
echo ÿ	especially with missile weapons.
echo ÿ
echo ÿ  If the character you are playing is paralyzed by the Vampire, in
echo ÿ  combat, do not hold down the attack button because the character
echo ÿ  will lose stamina.
echo ÿ
echo ÿ  In Overhead Mode, even with the "Alert" option on, you will not be
echo ÿ  given a warning on the begining of your turn if the opponent moves
echo ÿ  characters into sight and finishes their turn. So always look
echo ÿ  around before you move.
echo ÿ
echo ÿ  Frozen characters, on the strategy board, can still spot enemy
echo ÿ  characters.
echo ÿ
echo ÿ  Fire and Water Elementals are stopped by poison and insanity traps
echo ÿ  but take no damage.
pause
echo ÿ
echo ÿ  The charging Water Elemental and Orc will pass under the tips of
echo ÿ  the Vampire's wings without doing damage.
echo ÿ
echo ÿ  There is no way to cancel calibration of a joystick once you have
echo ÿ  begun.
echo ÿ
echo ÿ  If you set the computer level to merciless or difficult on small
echo ÿ  or tiny maps, keep the points down, or the computer's traps will
echo ÿ  hinder game play.
echo ÿ
echo ÿ  In combat, timing is crucial. If an attacking character is hit with
echo ÿ  an attack that is quicker while in mid-swing, then that attack will
echo ÿ	be spoiled or "interrupted". The interupted character will continue
echo ÿ	its attacking animation normally, but no damage will be done by the
echo ÿ  interrupted attack. However, certain awesomely powerful attacks
echo ÿ  cannot be interrupted:
echo ÿ  Demon           : both attacks
echo ÿ  Vampire         : both attacks
echo ÿ  Fire Elementral : mini-nova only
echo ÿ  Conjurer        : all three attacks
echo ÿ
echo ÿ
pause
echo ÿADDITIONAL NOTES ON MODEM and DIRECT LINK:
echo ÿ
echo ÿ  Modems that are not 100% Hayes compatible may experience problems
echo ÿ  while connecting. You may need to try the connection several times:
echo ÿ  be patient.
echo ÿ
echo ÿ  In order to make recovery from disconnections as convenient as
echo ÿ  possible, an autosave feature saves the game every turn. The last
echo ÿ  slot in the Load Game screen has been redesignated for this feature.
echo ÿ  If your game is interrupted, simply reconnect and load the Recover
echo ÿ  game, and you will have lost only a little time.
echo ÿ
echo ÿ  During modem or direct link, if one player is moving in Overhead
echo ÿ  Mode and the other player is viewing in 3D Mode with animations
echo ÿ  on, there will be a long delay between movements.
echo ÿ
echo ÿ  The Quick Start Games can be loaded for Modem and Direct Link
echo ÿ  games, even those set up for 1 player. This can save a lot of time
echo ÿ  in setup, and has the additional virtue of providing a consistent
echo ÿ  starting position for rematches. However, the player on the
echo ÿ	"computer" side may receive a considerable disadvantage in some
echo ÿ	quick start games.
echo ÿ
pause
echo ÿ  Warning: the "ESC" key will not pause the combat in modem or direct
echo ÿ  link. It will terminate the connection.
echo ÿ
echo ÿ  Warning: do not play with the keys in direct or modem link when it
echo ÿ	is the other player's turn.
echo ÿ
echo ÿ
echo ÿCHARACTER NOTES:
echo ÿ
echo ÿ  Berserker- No additional notes.
echo ÿ
echo ÿ  Conjurer- The type of characters that the Conjurer can conjure
echo ÿ  and the cost in Life Force is as follows:
echo ÿ          Demon            :20
echo ÿ          Fire Elemental   :15
echo ÿ          Phantom          :12
echo ÿ          Troll            :10
echo ÿ          Vampire          :20
echo ÿ          Water Elemental  :15
echo ÿ          Wraith           :18
echo ÿ  Note that conjured characters will lose Life Force as stated, but
echo ÿ  their regeneration rate is shown as 0 when viewed.
echo ÿ
pause
echo ÿ  Demon- The Demon's Death Cry is unable to kill characters on the
echo ÿ  strategy board, including illusions.
echo ÿ
echo ÿ  Fire Elemental- The Fire Elemental's flame suicide attack will not
echo ÿ  destroy illusions of Fire Elementals.
echo ÿ
echo ÿ  Illusionist- The Illusionist can create illusions of all characters
echo ÿ  except for Phantoms and Zombies. The cost in Life Force for each
echo ÿ  of the characters is:
echo ÿ          Berserker        :8
echo ÿ          Conjurer         :5
echo ÿ          Demon            :20
echo ÿ          Fire Elemental   :10
echo ÿ          Illusionist      :5
echo ÿ          Orc              :8
echo ÿ          Seer             :5
echo ÿ          Templar          :5
echo ÿ          Thief            :5
echo ÿ          Troll            :15
echo ÿ          Vampire          :20
echo ÿ          Water Elemental  :10
echo ÿ          Wizard           :8
echo ÿ          Wraith           :12
pause
echo ÿ  The cost to maintain an illusion is 10% ofthe creation cost. For
echo ÿ  example: an illusion of a Demon would cost the Illusionist two
echo ÿ  points of Life Force a turn to maintain.
echo ÿ
echo ÿ  Orc- The Orc, when charging, does more damage when the target is
echo ÿ  pinned against the border and obstacles than out in the open.
echo ÿ  The Orc's charge cannot be initiated within a minimum range of about
echo ÿ  one inch.
echo ÿ
echo ÿ  Phantom- Power rings will not increase the Phantom's taint in
echo ÿ  combat. Computer-run characters are able to tell exactly where
echo ÿ  your Phantoms are in combat, even though they appear to be
echo ÿ	invisible.
echo ÿ
echo ÿ  Seer-  The Seer's befuddle attack will make computer characters
echo ÿ  hesitate in combat. The computer's difficulty level will affect
echo ÿ  the amount of time that the characters hesitate. For example: on
echo ÿ  Hopeless level the hesitation will be very pronounced, and on
echo ÿ  Merciless, will hardly be noticeable. The Seer's agility in combat
echo ÿ	is more like a three than a four. The Seer's befuddle attack drains
echo ÿ	the enemy character's stamina. Once the character regains all their
echo ÿ  stamina they will throw off the effects of the befuddle. If you
echo ÿ	attack with a befuddled character then it will take you that much
pause
echo ÿ	more stamina to recover before the effects of the befuddle wear off.
echo ÿ
echo ÿ  Shape Shifter- The Shape Shifter in Phantom form is invisible
echo ÿ  on the strategic and tactical boards. If the Shape Shifter
echo ÿ  changes form at the begining of the turn, then the Shape Shifter
echo ÿ  will retain the movement for the previous form for the rest of that
echo ÿ  turn. For example: if the Shape Shifter was a Troll and changes to
echo ÿ  a Vampire, the Shape Shifter will still retain the movement of the
echo ÿ  Troll. The Shape Shifter is immune to the traps that the current
echo ÿ  form is normally immune to. If the Shape Shifter changes into a
echo ÿ  form with less Life Force than the Shape Shifter's maximum (50) then
echo ÿ  the Shape Shifter will have the Life Force of the new form.
echo ÿ
echo ÿ  Templar- The Templar is able to heal, in a limited capacity,
echo ÿ  characters that are near the Templar. If the character is in the
echo ÿ  adjacent square, then that character will receive two points of
echo ÿ  Life Force per turn. If the character is two squares away, then
echo ÿ  that character will receive one point of Life Force per turn.
echo ÿ  The Templar is unable to use his special healing on characters
echo ÿ  with a negative or zero revitalization. The special healing gives
echo ÿ  three times the revitalization of the character being healed. For
echo ÿ  example: the Templar healing a Wizard would give that character
echo ÿ  six points of Life Force. If charaters have Ring(s) of
pause
echo ÿ  Rejuvenation they will not be included in the multiple when the
echo ÿ  character is being healed by a Templar.
echo ÿ
echo ÿ  Thief- Make sure that you want to disarm a trap before you go to
echo ÿ  the "Decrypt Trap" screen because there is no going back once
echo ÿ  there. Manually disarming a trap: choose a symbol that is going
echo ÿ  to lead you in the right direction (follow the arrows). If the
echo ÿ  first couple of slots are open, make your best guess to start.
echo ÿ
echo ÿ  Troll- The Troll does not regenerate Life Force while in rock
echo ÿ  form, so make sure that you have enough Life Force to change
echo ÿ  back into Troll form or you are trapped! Be careful to remember
echo ÿ	which Trolls you turned into rocks, for there is no identifying
echo ÿ	marks to remind you.
echo ÿ
echo ÿ  Vampire- If you make a Zombie out of a character that had rings
echo ÿ  then those rings no longer function. In a Vampire vs. Vampire
echo ÿ  combat, if one of the Vampires gets paralyzed with its tongue
echo ÿ  out, then that Vampire will not get any stamina back until its
echo ÿ  tongue is retracted and is unparalyzed. Vampires are unable to
echo ÿ  make Zombies out of conjured characters. If the Vampire is the
echo ÿ  Orb Holder and is the last of you characters, then no matter how
echo ÿ  many Zombies you make your Vampire's life regeneration will still
pause
echo ÿ  be -5.
echo ÿ
echo ÿ  Water Elemental- The Water Elemental, when charging, will do more
echo ÿ  damage when the target is pinned between the borders and obstacles
echo ÿ  than out in the open.
echo ÿ
echo ÿ  Wizard- If the Wizard tries to freeze a Water Elemental, in combat,
echo ÿ  as the Elemental is using its Tidal Wave attack, the Water
echo ÿ  Elemental's attack will not be stopped. The minimum range for the
echo ÿ  Wizard's strategic freeze attack is three squares. The maximum range
echo ÿ  is six squares. The damage caused by the freeze is ten points of
echo ÿ  Life Force. The frozen character will be frozen for one turn
echo ÿ  for every time that the character was hit with a freeze. In combat,
echo ÿ  if the Wizard uses his freeze attack on any character that is
echo ÿ  within about two inches of the Wizard, then the freeze ball will
echo ÿ	pass through the character and do a small amount of damage without
echo ÿ  freezing that character.
echo ÿ
echo ÿ  Wraith- The Wraith's special power "Teleport" costs ten points of
echo ÿ  Life Force initially and one point for every square that the
echo ÿ  Wraith teleports. The Wraith's double grope attack does the same
echo ÿ  amount of damage as the single swipe, but gives the Wraith four
echo ÿ  times as much Life Force. The Wraith's agility is rated as a
pause
echo ÿ  seven, but because the Wraith must first extend its arms, the
echo ÿ  character is a little slow starting off.
echo ÿ
echo ÿ  Zombie- Zombies are unable to move on the first turn of creation.
echo ÿ
echo ÿThanks for playing Dark Legions!
echo ÿÿÿ