ECHO OFF
CLS
echo To start a program read the documentation files first!
echo To print out docs type the following command: MANUAL   (PRESS ENTER)
echo (Make sure printer is on line and loaded with paper first)
echo Let printer stop printing before typing in any additional command.
echo TO RECEIVE YOUR FREE CATALOG OF OVER 1000 UNUSUAL AND UNIQUE PC COMPATIBLE
echo PROGRAMS PRICED AS LOW AS $1.99 PER PROGRAM DISK, CALL OR WRITE:

echo                                           SHAREWARE TO GO
echo                                           P.O. BOX 574575
echo                                           ORLANDO, FL  32857
echo                                           TEL (407) 679-5159

echo "AMERICA'S BEST BUY IN SOFTWARE FOR AS LITTLE AS $1.99 EACH!"                                           
ECHO ON