echo off
echo ÿ
echo                 ****  HARD DISK INSTALLATION ****
echo ÿ
echo ÿ
echo ÿ
echo Guardians need 400ko. Make sure you have enough space on your disk C:
echo        Type CTRL-C if you want to abord the installation
echo            or any other key if you want to continue
pause
echo ÿ
echo ÿ
echo                        ... running ...
md c:\guardian
copy *.* c:\guardian
echo ÿ
echo ÿ
echo Installation finished...
echo to play, type :
echo       C:
echo       CD \GUARDIAN
echo       GUARDIAN
echo ÿ
