REM DACTYLUS "Die Geschichte einer Rache" Batch File Beispiel

@echo off

REM Kopieren Sie diese Batch Datei in ein Verzeichnis auf welches der
REM Path zeigt ( z.B. C:\DOS ) und Ñndern Sie die folgende Zeile so
REM ab, das sie in das Dactylus Verzeichnis springt. Lîschen Sie
REM das "REM" am Anfang dieser Zeile um der Anweissung gÅltigkeit
REM zu verleihen, verfahren sie mit der darauf folgenden Zeile genauso!

REM cd c:\spiele\dactylus
REM c:

Dactylus.com