echo off
cls
echo                 MIXED-UP MOTHER GOOSE README FILE
echo                           July 31, 1990
echo.
echo.
echo  The intention of this Readme file is to inform you of possible
echo  problems with the program and updates to the documentation.
echo.
echo  The following problem has been reported in Version 1.0.
echo.
echo       When playing MIXED-UP MOTHER GOOSE from 360K floppy disks,
echo       be aware that your Save Game disk (which should be a blank,
echo       formatted disk) can hold a maximum of 8 saved games.  If
echo       you create a ninth kid, this will overwrite your 8th saved
echo       game and you will be unable to restore your 8th game.
echo.
echo       We strongly suggest that players using 360K floppies 
echo       restrict themselves to 7 saved games per Save Game disk.
echo       This will prevent any possibility of accidentally 
echo       creating and/or overwriting your 8th Saved Game.  When
echo       creating an 8th kid, insert a fresh, blank formatted
echo       Save Game disk.
echo.
pause
echo       Alternatively, you may choose to delete old saved games
echo       from your Save Game disk.
echo.
echo       This problem does not apply to those using 720K disks,
echo       high density disks, or a hard drive to play MIXED-UP MOTHER
echo       GOOSE.
echo.
pause