echo off
cls
echo.
echo.
echo         Mindscape Presents
echo     Angelsoft Interactive Fiction
echo.
echo           INDIANA JONES (tm)
echo                 IN
echo     REVENGE OF THE ANCIENTS (tm)
echo.
echo.
echo (tm) Game elements and character names
echo and likenesses are trademarks of
echo Lucasfilm Ltd.  Used by Mindscape, Inc.
echo Authorized User.  Program contents
echo developed by Angelsoft, Inc.
echo.
echo Copyright (c) 1987 Lucasfilm Ltd. and
echo Mindscape, Inc.  All rights reserved.
echo.
echo.
echo.
echo.
echo.
pause
game

