@echo off
cls
echo.
echo ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
echo บ SARGON 4 Version 1.01 and Later                              บ
echo บ                                                              บ
echo บ PLEASE NOTE:                                                 บ
echo บ                                                              บ
echo บ     If you are a SARGON 4 (version 1.00) or a SARGON 3 owner บ
echo บ and wish to use saved games you created with either of these บ
echo บ products, you must run the utility (CONVERTG.EXE) on those   บ
echo บ game files (only the ones YOU made.) The file structure has  บ
echo บ been enhanced, making the program incompatible with previous บ
echo บ versions.                                                    บ
echo ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
echo.
echo If you wish to read about using the CONVERTG.EXE program now, press
echo any key. Press CNTRL C (or CNTRL BREAK) to exit, and answer Y.
echo.
echo 					- Spinnaker Software
echo 					  September, 1989
echo.
PAUSE
CLS
echo.
echo ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
echo บ CONVERTG.EXE : Usage                                         บ
echo บ                                                              บ
echo บ To convert a game saved by a previous version of SARGON,     บ  
echo บ type the program name followed by the filename of the game.  บ
echo บ You do not need to specify the extension .GAM which is auto- บ
echo บ matically added. The following is an example of the command  บ
echo บ used on a user game whose filename is RALPH1.GAM and which   บ
echo บ is in the games directory:                                   บ
echo บ                                                              บ
echo บ               CONVERTG GAMES\RALPH1                          บ
echo บ                                                              บ
echo บ You may specifiy wildcards so the following command selects  บ
echo บ all the game files in present (default) directory:           บ
echo บ                                                              บ
echo บ               CONVERTG *.GAM   (or CONVERTG *.*)             บ
echo บ                                                              บ
echo ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
echo.
