@echo off
cls
echo ÿ
echo °°°°°°±±±±±±±²²²²²²²²  Welcome to the CD-ROM version of  ²²²²²²²²±±±±±±±°°°°°°
echo °°°°°°±±±±±±±²²²²²²²²            K A R N O V             ²²²²²²²²±±±±±±±°°°°°°
echo ÿ                                   
echo                            PLAYING FROM THE CD-ROM 
echo                            ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ  
echo  To play KARNOV directly off the CD, type KARNOV at the CD-ROM drive prompt.
echo ÿ
echo             Example D:\KARNOV  (where D:\ is your CD-ROM drive). 
echo   If your ROM drive is not D: simply replace D: with the appropriate letter. 
echo ÿ
echo                            INSTALLING TO HARD DISK
echo                            ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ            
echo  If you wish to install the game to your computer's hard disk drive, simply
echo  copy ALL the files from the CD-ROM to a directory of your choice on your 
echo  hard drive. Use the same command (KARNOV) to play the game.
echo ÿ
echo           This game requires less than 1 Megabyte of free disk space.
echo ÿ
echo           ==========================================================
echo            There is a manual for KARNOV in a file called KARNOV.TXT 
echo           ==========================================================
echo ÿ
echo °°°°°°°±±±±±±±±²²²²²²²²²²      Have fun playing      ²²²²²²²²²²±±±±±±±±°°°°°°°
echo °°°°°°°±±±±±±±±²²²²²²²²²²        K A R N O V !       ²²²²²²²²²²±±±±±±±±°°°°°°°

