echo off

rem *** Beverly Hills Cop
rem *** (c) Tynesoft Computer Software 1989
rem *** All rights reserved

rem *** Game controller system  : Gary Partis
rem *** Demo and hi-score table : Gary Partis
rem *** Game 1                  : Scrapped
rem *** Game 2                  : Gary Partis
rem *** Game 3                  : David Crofts
rem *** Game 4                  : David Crofts
rem *** Game 5                  : Game Partis

if errorlevel 1 goto error
loadfix bhcg0.com
:error
echo on

