@echo off
cls
echo.
echo ==========  BACK TO THE MOON  V:1.1  ==========
echo.
echo ATEN€ŽO!  Este programa ‚ distribu¡do como FREEWARE, ou seja, vocˆ n„o paga
echo nada por ele. Vocˆ pode distribuir c¢pias para seus amigos ou fazer um
echo "upload" em sua BBS ou at‚ distribui-lo em CD-ROMs de shareware. Por esse 
echo motivo o programa ‚ fornecido "como ‚", sem nenhum tipo de garantia ou
echo obriga‡„o por parte do autor.
echo.
echo Se vocˆ n„o concorda com os termos acima, n„o instale o programa em seu
echo computador. Se j  instalou, apague-o. Ao manter uma c¢pia do BACK TO THE MOON
echo em seu computador vocˆ estar  automaticamente concordando com os termos acima
echo citados.
echo.
echo ================ INSTALA€ŽO ===================
echo.
echo Para instalar o jogo em seu computador coloque o disquete de instala‡„o
echo no drive A ou B. 
echo Tecle A: (ou B:) seguido da tecla Enter e depois tecle INSTALL tamb‚m
echo seguido da tecla Enter. Ou tecle diretamente A:INSTALL e Enter
echo Tecle E ou P para ver as mensagens em Inglˆs ou Portuguˆs e siga as
echo instru‡”es fornecidas pelo programa.
echo.
pause
cls
echo Para executar o programa ap¢s a instala‡„o, entre no diret¢rio MOON com
echo o comando CD\MOON e execute o programa teclando MOON e Enter.
echo N„o recomendo execut -lo sob o Windows 3.xx, pode haver conflito entre os
echo drivers para placa de som.
echo * IMPORTANTE: Se vocˆ intalou o jogo diretamente, sem o programa install, n„o
echo se esque‡a de executar o SETUP para configurar a(s) placa(s) de som.
echo.
echo Requisitos m¡nimos de Hardware:
echo.
echo   - PC 386 DX33 ou superior, 486 recomendado;
echo   - 562 kb (575.186 bytes) a 584 kb (597.715 bytes) de mem¢ria base dispon¡vel
echo     dependendo dos tipos de drivers de som e m£sica carregados, por exemplo:
echo     S„o necess rios 582 kb (595.731 bytes) com os drivers para SoundBlaster;
echo   - Disco r¡gido com 1.840 kb (1.883.859 bytes) livres ou mais; 
echo   - Monitor de v¡deo VGA ou compat¡vel;
echo   - Placa de som (opcional).
echo.
echo Para se obter o melhor das m£sicas contidas neste jogo recomenda-se a
echo utiliza‡„o de um m¢dulo ou placa de som do padr„o General MIDI, como a
echo Sound Blaster AW16 ou 32, que dever„o estar devidamente configuradas.
echo Sintetizadores e teclados General MIDI tamb‚m podem ser utilizados se
echo conectados atrav‚s de uma interface MIDI como por exemplo a MPU401.
echo.
pause
cls
echo ================= Problemas e solu‡”es ====================
echo.
echo P: Ao tentar instalar o programa nenhum disco r¡gido que eu seleciono ‚
echo    aceito pelo programa de instala‡„o.
echo S: Tente livrar mais espa‡o em seu disco r¡gido, provavelmente a falta de
echo    espa‡o ainda ‚ o problema.
echo.
echo P: Ao rodar o jogo aparece s¢ a mensagem "Loading..." e o computador trava.
echo S: Certifique-se que vocˆ est  no diret¢rio MOON antes de executar o programa.
echo    Outra causa pode ser o fato de vocˆ ter abortado a configura‡„o da placa de
echo    som. O programa REQUER que um driver seja selecionado para o som digital e
echo    um outro driver seja selecionado para m£sica, mesmo que seja o da op‡„o
echo    "Nenhuma placa de som" ou "PC Speaker". Se realmente vocˆ n„o quer nenhum
echo    ru¡do, entre no menu "Op‡”es" no jogo e desligue os Efeitos e a M£sica.
echo.
echo P: Sempre que tento rodar o programa aparece a seguinte mensagem:
echo    "ERRO FATAL: Imposs¡vel alocar mem¢ria ........"
echo S: Vocˆ precisa liberar mais mem¢ria convencional para o jogo. Uma forma simples
echo    de fazˆ-lo ‚, ao ligar o computador, teclar F5 durante a inicializa‡„o
echo    do DOS para pular a execu‡„o do CONFIG.SYS e do AUTOEXEC.BAT.
echo    Se isto n„o resolver, tecle F8 ao inv‚s de F5 e responda sim apenas para
echo    o HIMEM.SYS e o DOS=HIGH (ou DOS=HIGH,UMB).
echo.
pause
cls
echo P: Tudo funciona bem mas o volume da m£sica est  muito alto ou muito baixo
echo    em rela‡„o ao efeitos sonoros. O que fazer?
echo S: Utilize o utilit rio DOS de sua placa de som que ajusta o volume da m£sica
echo    e do som digital e escolha os n¡veis mais apropriados. Cada placa tem seu
echo    tipo de programa que pode se chamar MIXER, MIXSET, SETSOUND, etc.
echo.
echo P: Meu joystick n„o funciona com este jogo. O que acontece?
echo S: Infelizmente este jogo n„o foi feito para joystick, s¢ teclado.
echo.
echo P: Fiz a instala‡„o corretamente, mais de uma vez at‚, mas sempre que rodo
echo    o jogo aparece uma janela com a mensagem de "Arquivo corrompido", ou …s
echo    vezes o programa at‚ roda depois trava, com a mensagem "STACK OVERFLOW".
echo S: Se a instala‡„o foi feita corretamente e realmente n„o h  arquivos com
echo    defeito ou faltando provavelmente o problema ‚ que vocˆ est  no limite
echo    da mem¢ria necess ria e n„o sobrou espa‡o para os manipuladores de
echo    arquivos do jogo.
echo.
echo P: Alguns sons parecem cortados e se interropem no meio. Por exemplo:
echo    Ao inv‚s de falar "Ok. Ready to return" ele diz "Ok. Ready to ret".
echo S: Vocˆ provavelmente est  com o m¡nimo de mem¢ria necess ria, por isso
echo    o programa "corta" alguns sons para poder livrar um pouquinho mais.
echo.
echo.
pause
cls
echo.
echo ==========  BACK TO THE MOON  V:1.1  ==========
echo.
echo Se vocˆ apreciou este jogo, assim como a iniciativa de desenvolvˆ-lo,
echo sua contribui‡„o ‚ muito bem-vinda.
echo Vocˆ estar  colaborando para o desenvolvimento de novos jogos, muito mais
echo elaborados, que ser„o distribu¡dos no futuro como Shareware e Freeware.
echo Contribui‡”es de US$10.00 (ou o valor equivalente) far„o com que seu nome
echo seja inclu¡do na lista de pessoas que receber„o o BACK TO THE MOON II, e
echo outros jogos em desenvolvimento.
echo Coment rios e sugest”es tamb‚m s„o bem-vindos.
echo.
echo Envie para:
echo.
echo   RICARDO A. BARIJAN
echo   Rua Coriolano O. Barbosa 16
echo   13086-120
echo   CAMPINAS - SP
echo   BRAZIL
echo.                                                       Ver: 1.1
echo.Email: barijan@usa.net                               Mar‡o de 1997
echo.
echo.
