@echo off
cls
echo.
echo ==========  BACK TO THE MOON  V:1.0  ==========
echo.
echo ATTENTION!!!  This software is distributed as FREEWARE. That means that you
echo don't have to pay anything for this. You can give copies to your friends and
echo can upload it to your BBS, or even distribute it in CD-ROMs. For this reason 
echo the software is provided "as is", without any kind of guarantee or obligation 
echo from the author.
echo.
echo If you don't agree with the terms above, don't install the game in your
echo computer. If you did it already, please delete it right away. Keeping a copy
echo of BACK TO THE MOON in your computer, you automatically agree with the terms
echo listed above.
echo.
echo ===============  INSTALLATION  ================
echo.
echo To install the game, put the installation disk on the disk driver A or B.
echo Type A: (or B:) followed by Enter key and so type INSTALL followed by the
echo Enter key too, or just type directly A:INSTALL and Enter.
echo Press E or P to see the messages in English or Portuguese and follow the
echo directions provided by the INSTALL program.
echo.
pause
cls
echo To run the program after the installation, enter in the MOON directory with
echo CD\MOON and run the game typing MOON and Enter.
echo I don't recommend to run it under Windows 3.xx, you may experiment conflicts 
echo with the sound drivers.
echo * IMPORTANT: If you have installed it directly, without the INSTALL, you must
echo to run the SETUP program in order to configure the sound hardware.
echo.
echo Hardware requirements:
echo.
echo   - PC 386 DX33 or better, 486 recommended;
echo   - 562 kb (575,186 bytes) to 584 kb (597,715) of free base memory. It depends
echo     of the type of sound and music drivers loaded. For example: You will need
echo     at least 582 kb (595,731 bytes) if using the drivers for the SoundBlaster;
echo   - Hard disk with 1,840 kb (1,883,859 bytes) available or more;
echo   - VGA or compatible;
echo   - Sound board (optional).
echo.
echo To obtain the best performance of the music of this game we recommend to use
echo a General MIDI module or sound board, such as Sound Blaster AW16 or 32, but
echo it must to be properly configured to work with DOS programs in General Midi.
echo General MIDI Synthesizers and keyboards can be used also if properly connected
echo trough a MIDI interface, such as the MPU401.
echo.
pause
cls
echo =================  TROUBLESHOOTING ===================
echo.
echo Q: When trying to install the software none of the hard disks that I select
echo    Is accepted by the installation program. What's wrong?
echo A: Try to free some more space on your hard disk. Probably you have no enough
echo    free space for the installation.
echo.
echo Q: Why when I run the game I got just the "Loading..." message and crash?
echo A: Be sure that you are on the MOON directory before run the game.
echo    Another cause can be the you have aborted the sound card configuration.
echo    The program REQUIRES a sound driver, even if this driver is the "No digital
echo    sound card" or "PC Speaker" options. If you really don't want any kind of
echo    noise go to the game menu "Options" and disable the Effects and Music.
echo.
echo Q: What means when I try to run the game and the following message appears:
echo    "FATAL ERROR: Impossible to allocate memory ......."?
echo A: You need to free some more base memory for the game. A easy way to do that
echo    is press F5 during the DOS initialization, after you have turned the
echo    computer on, in order to skip the CONFIG.SYS and the AUTOEXEC.BAT.
echo    If it doesn't solve the problem press F8 instead and answer yes just to
echo    the commands HIMEM.SYS and DOS=HIGH (or DOS=HIGH,UMB).
echo.
echo.
pause
cls
echo Q: Everything is fine but the music, that is too much higher or lower than the
echo    sound effects. What to do to solve this?
echo A: Use the proper DOS utility that is provided with your sound card to adjust
echo    the music and the digital sound volume and set it to better levels. Each
echo    board have their own program and can be called MIXER, MIXSET, SETSOUND, etc.
echo.
echo Q: Can I use my joystick with this game?
echo A: No. This game was designed to be played using the keyboard.
echo.
echo Q: Why I got a "File corrupt" message even if I have installed all the files
echo    successfully? Sometimes it runs but later it crashes with "STACK OVERFLOW".
echo A: If you really installed it correctly the problem may be that you are
echo    running on the limit of the necessary memory and there is no space for
echo    the game internal file handlers.
echo.
echo Q: Some sounds seems to be clipped. For example: When it's supposed to be 
echo    heard "Ok. Ready to return" it sounds "Ok. Ready to ret" instead. Why?
echo A: You probably are running with the minimum of the necessary memory, so
echo    the program "cut" some sounds to free some more memory.
echo.
echo.
echo.
pause
cls
echo.
echo ==========  BACK TO THE MOON  V:1.1 ==========
echo.
echo If you have enjoyed this game and appreciate the initiative of the programmer,
echo your contribution is most welcome.
echo You will be helping the development of new and more sophisticated games,
echo which will be distributed as shareware and freeware.
echo Contributions of US$10.00 or more will put your name on the list of people
echo to receive the BACK TO THE MOON II and other games currently being developed.
echo Comments and suggestions are welcome also.
echo.
echo Send to:
echo.
echo   RICARDO A. BARIJAN
echo   Rua Coriolano O. Barbosa 16
echo   13086-120
echo   CAMPINAS - SP
echo   BRAZIL
echo.                                                      Ver 1.1
echo Email: barijan@usa.net                              May of 1997
echo.
