ECHO OFF
A:
SETUPCOM
CLS
ECHO 		------ DEFCON5 Version 1.3 ------
ECHO IF YOU WISH TO SETUP DEFCON 5 ON THE HARDDISK THEN PRESS ANY KEY.
ECHO IF YOU DO NOT THEN HOLD DOWN THE Ctrl KEY AND PRESS C THEN Y.
PAUSE 
:HARD
ECHO HARD DISK INITIALIZATION
C:
CD\
MKDIR DEFCON
CD\DEFCON
COPY A:*.*
PAUSE PLEASE PLACE DISK2 IN DRIVE A
COPY A:*.*
:END

