@ECHO OFF
ECHO -------------------------------------------------------------------
ECHO UNREAL PC is autobooting.
ECHO -------------------------------------------------------------------
ECHO UNREAL original version by Art & Magic.
ECHO This version reworked by Tim McCarthy, Mike Talbot & Richard Cheek.
ECHO (C) UBISoft 1991.
ECHO -------------------------------------------------------------------
cd unreal
unreal