echo off
cls
if x%1==x1 instalu2 install.ls1
if x%1==x1 goto exit
if x%1==x2 instalu2 install.ls2
if x%1==x2 goto exit
echo   ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
echo   บ                     Villa Crespo Software                    บ
echo   บ             Stanford Wong VIDEO POKER Installation           บ
echo   ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
echo   บ   Please enter at the DOS prompt:                            บ
echo   บ      INSTALL 1    if you have  EGA, VGA, or TANDY Graphics   บ
echo   บ      INSTALL 2    if you have  CGA only                      บ
echo   ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
echo   ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
:EXIT
