@ECHO OFF
CLS
ECHO *****************************************************************************
ECHO *             Evil Crypt, Copyright 1985, 1992 by Curtis Keisler            *
ECHO *                                                                           *
ECHO * Please read the documentation BEFORE playing the game.  That way you will *
ECHO * enjoy the game more.  I promise!                                          *
ECHO *                                                                           *
ECHO * The following is a description of the files that you should have received *
ECHO * in the zip file, EC.ZIP:                                                  *
ECHO *                                                                           * 
ECHO * EC.EXE       - The executable program, Evil Crypt.                        *
ECHO * EC.DOC       - Instructions and background on the game.  It also includes *
ECHO *               a registration form should you become addicted to the game. *
ECHO * ECPRINT.BAT  - A batch file that will print the documentation for you.    *
ECHO * ECREADME.BAT - You are reading it now.                                    *
ECHO *****************************************************************************