echo off
echo Installing Steel Empire onto c:\steel
echo Press any key to proceed
pause > nul
echo Making directory c:\steel from
mkdir c:\steel
echo Please make sure the main disk is in the drive and press any key.
pause > nul
copy *.* c:\steel
echo Please make sure the map  disk is in the drive and press any key.
pause > nul
copy *.* c:\steel
echo Please make sure the vga  disk is in the drive and press any key.
pause > nul
copy *.* c:\steel
