ECHO OFF
CLS
ECHO _____________________________________________________________________
ECHO !                                                                   !
ECHO !                     *******************************               !
ECHO !                     *      FOOTBALL  MANAGER      *               !
ECHO !                     *      WORLD CUP EDITION      *               !
ECHO !                     *******************************               !
ECHO !                                                                   !
ECHO !                                                                   !
ECHO ! To run type:-                                                     !
ECHO !          CGA   - for the CGA version                              !
ECHO !          EGA   - for the EGA/VGA version                          !
ECHO !          TANDY - for the Tandy version                            !
ECHO ! and then press the [RETURN] key                                   !
ECHO !                                                                   !
ECHO !-------------------------------------------------------------------!
ECHO ON