Echo off
cls
Echo ÿ
Echo ÿ
Echo        ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²
Echo        ²² PERSYARATAN KLAIM ATAS SOFTWARE PT ELEX MEDIA KOMPUTINDO ²²
Echo        ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²
Echo ÿ
Echo       Klaim atas software PT Elex Media Komputindo dapat dilayani bila
Echo       memenuhi persyaratan :
Echo ÿ
Echo       1. Disket tidak tergores(rusak fisik).
Echo       2. Melampirkan bon pembelian,  dengan tanggal klaim  tidak lebih
Echo          dari satu bulan setelah membeli disket tersebut.
Echo       3. Mengirim kembali secara utuh semua kelengkapan  disket sesuai
Echo          dengan judul software yang Anda klaim.
Echo       4. Gunakan lembar kardus pengaman, supaya terhindar dari goresan
Echo          dan lipatan selama dalam perjalanan pengiriman ke tempat kami
Echo       5. Lampirkan perangko untuk balasan,  mencatat permasalahannya,
Echo          mencatat judul software yang Anda klaim  juga  jenis komputer    
Echo          yang dipakai:  XT, AT 286, 386,486 atau yang lain.
Echo       6. Catat dan lampirkan isi file  CONFIG.SYS serta AUTOEXEC.BAT 
Echo          yang digunakan untuk menghidupkan komputer.
Echo ÿ
Echo        TERIMA KASIH ATAS PEMAKAIAN SOFTWARE KAMI   ³³¯   PT ELEX MEDIA
Echo       +++++++++++++++++++++++++++++++++++++++++++  ¯³³      KOMPUTINDO
Echo                                                     TIM SOFTWARE HOUSE ÿ
Echo  ÿ
