ECHO OFF
CLS       
ECHO.
ECHO             ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO             บ  EGA OR VGA GRAPHIC ARE RECOMMENDED FOR THIS PACKAGE. บ
ECHO             บ   THIS PROGRAM WILL RUN FASTER FROM YOUR HARD DRIVE.  บ
ECHO             ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO            ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO            บ  THIS PACKAGE WILL TEACH YOUR CHILD HOW TO: SAY EARLY   บ
ECHO            บ  WORDS, LEARN THE ALPHABET, READ, SPELL WORDS AND MUCH  บ
ECHO            บ  MUCH MORE. ALSO INCLUDED IS THE ABC SONG, COLORFUL     บ
ECHO            บ  ALLURING GRAPHICS AND EASY DRAW FOR THEIR CREATIVITY.  บ
ECHO            ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO           ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO           บ PLEASE, GIVE THIS PACKAGE TO OTHER PARENTS WITH CHILDREN. บ
ECHO           ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO          ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO          บ 123-TALK IS ALSO AVAILABLE. 123-TALK WILL TEACH YOUR CHILD: บ
ECHO          บ NUMBERS, COUNTING, ADDITION, SUBTRACTION, PHONE # AND MORE. บ
ECHO          ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO         ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO         บ THIS IS A UNREGISTERED COPY OF ABC-TALK, IF YOU CONTINUE TO   บ
ECHO         บ USE THIS PROGRAM, PLEASE REGISTER YOUR SHAREWARE. IT'S ONLY   บ
ECHO         บ $29.50, THAT A SMALL PRICE TO PAY FOR YOUR CHILD'S EDUCATION. บ
ECHO         ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
ECHO OFF
ABC-TALK
ECHO ON