echo off
echo                         COVERT ACTION (TM)         10/20/90
echo .
echo The following information was implemented/changed after the
echo Technical Supplement went to press.
echo .
echo INSTALLATION FROM DRIVE B:
echo         Use the command BINSTALL instead of INSTALL if you wish to
echo         install COVERT ACTION from Drive B:.
echo .
echo HALL OF FAME
echo         The Hall of Fame data is kept in a file called FAME.DTA and
echo         may be copied or moved like any DOS file. When the Hall of
echo         Fame appears in the game the 'C' key will clear the file
echo         except for the current entry. When reviewing the Hall of
echo         Fame pressing '1' through '5' will recall Max's vacation
echo         snapshot for that particular case!
echo .
echo COLUMBIAN CARTEL
echo         The organization refered to as the Cali Cartel in the 
echo         Technical Supplement is known in the game as the
echo         Columbian Cartel (CCart, Columbian Crt).
echo .
PAUSE
echo DOUBLE AGENTS
echo         Double Agents within the CIA no longer provide false clues.
echo         They do, however, notify enemy organizations when you are
echo         in their city.  If the enemy seems unusually alerted to your
echo         presence in town, this may indicate a double agent. You may
echo         also find information revealing double agents in floor safes
echo         within enemy buildings.
echo .       
echo USE OF COMPUTER TERMINALS
echo         It is possible (especially at the higher difficulty levels)
echo         for the alarm to be set off when accessing an computer
echo         terminal.
echo .
echo MISSION SCORE
echo         It is possible (but extremely difficult) to score above 1000
echo         points for a single case.
echo .
echo LENGTH OF CAREER
echo         At the end of ten years, it will be time for Max to retire.
echo .
PAUSE
echo JOYSTICK        
echo         The JoyStick may not be used during the car chase and code
echo         breaking portions of the game.
echo .
echo ROLAND SOUND 
echo         In order to assure proper operation, please remove any other
echo         MIDI input connections when using Roland sound hardware. 
echo .
echo SOUND DRIVERS
echo         In the future, MicroProse may supply custom sound drivers
echo         for new sound boards.  To install one of these drivers, 
echo         copy it into your \MPS\COVERT directory (disk A if on floppies),
echo         rename the driver program to XSOUND.EXE, and select 'Custom
echo         sound driver' when starting the game.
echo .
PAUSE
echo on    

