@echo off
rem ***  The first known attempt at MS-DOS adventuring    ***
rem *** Launched by Johbe and Frera on 30:th of March '93 ***
rem ***             Updated in December 2001              ***

set hbr=home
set hb1=chest
set hb2=rivendell
set hb3=gandalf
set hb5=woods
set hb6=cave
set hb7=den
set hbs=NO

echo Hobbit - The True Story - redux, Director's Cut.
echo.
echo An MS-DOS adventure released by Milbus Software (tm) 1993.
echo redux, Director's Cut released by Milbus Software (tm) 2001.
echo.
call look

