echo off
cls
echo	      IMPORTANT!  When calibrating the joystick, the manual
echo       incorrectly instructs you to let go of the joystick after
echo       you've pressed the appropriate number key on the numeric
echo       keypad.  Instead, after pressing the number key, DO NOT
echo       let go of the joystick.  It must remain in position
echo       until after the arrow turns green when you press the 
echo       plus or minus keys.
pause
echo       Tandy 1000 owners!  When calibrating the joystick,
echo       use the down-arrow and right-arrow to move the yellow
echo       bar toward the green bar instead of the plus and minus
echo       keys as documented in the manual.
pole2
