echo off
echo ÝUPDATED 7/16/93
echo Ý
echo Ý
echo Ý
echo Ý
echo ÝThank for supporting MoraffWare.
echo Ý
echo ÝThis is Moraff's Monster Bridge, Advanced Version 2.1, copyright, 1993.
echo ÝMoraff's Stones is contained inside Monster Bridge.
echo Ý
echo ÝStart these games by typing 'MBRIDGE'
echo Ý
echo ÝThank you for your support and please enjoy this game!
echo Ý
echo Ý
echo Ý
echo Ý
echo Ý
echo Ý

