echo off
cls
echo.
echo  SOUND BLASTER version of 123-TALK is now available.
echo  컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
echo.
echo  Learning numbers is lots of fun with this new interactive talking
echo  program that features REAL human SPEECH and sounds that works thru  
echo  your SOUND BLASTER or compatible.  Your child will learn how to say 
echo  numbers, counting, addition, subtraction, singing, drawing and much 
echo  more.  Lead your child into the next century with this package.  You 
echo  can record your own voice files and add them to 123-TALK. * WOW *
echo.
say_sb 123sb.voc
echo  Call 1-800-327-3929 to order 123-TALK for SOUND BLASTER.
echo       ~~~~~~~~~~~~~~
echo  Or send $25.00 US dollars to:
echo                                DareWare Inc.
echo                                3005 Glenmore Ave.
echo                                Balto., MD 21214  USA
echo                                (410) 665-0193
echo.
say_sb 123sb.voc
echo                                THANK YOU FOR YOUR SUPPORT
echo.
pause