ECHO OFF
CLS       
ECHO.
ECHO            ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO            บ    THIS PROGRAM WILL RUN FASTER FROM YOUR HARD DRIVE.   บ
ECHO            ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO           ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO           บ  THIS PACKAGE WILL TEACH YOUR CHILD HOW TO: SAY NUMBERS,  บ
ECHO           บ  COUNTING, REMEMBER PHONE NUMBERS, ADDITION, SUBTRACTION, บ
ECHO           บ  AND MUCH MORE. ALSO INCLUDED IS THE 123 SONG, COLORFUL   บ
ECHO           บ  ALLURING GRAPHICS AND EASY DRAW II FOR THEIR CREATIVITY. บ
ECHO           ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO           ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO           บ PLEASE, UPLOAD THIS PACKAGE TO YOUR LOCAL BULLETIN BOARD. บ
ECHO           ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO          ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO          บ ABC-TALK IS ALSO AVAILABLE. ABC-TALK WILL TEACH YOUR CHILD: บ
ECHO          บ EARLY WORDS, THE ALPHABET, READING, SPELLING AND MUCH MORE. บ
ECHO          ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO         ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO         บ THIS IS A UNREGISTERED COPY OF 123-TALK, IF YOU CONTINUE TO   บ
ECHO         บ USE THIS PROGRAM, PLEASE REGISTER YOUR SHAREWARE. IT'S ONLY   บ
ECHO         บ $25.00, THAT A SMALL PRICE TO PAY FOR YOUR CHILDS EDUCATION.  บ
ECHO         ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
ECHO OFF
123_TALK
ECHO ON