echo off
echo ÝThank you for your purchase of Dungeons of the Unforgiven.    Updated 5/6/95
echo Ý
echo ÝIf you are running any memory resident programs, you may have to remove them
echo Ý  to run this game. It requires a full 640k and only runs in base RAM.
echo ÝPlease do not use your master disks as play disks. Use copies of the masters.
echo Ý
echo ÝType 'UNFORGIV' to begin the game. Don't run Unforgiven from the master disk!
echo Ý
echo ÝMoving players from Moraff's World to Unforgiven:
echo Ý1) First make a backup copy of your Moraff's World directory.
echo Ý2) Get into your Moraff's World directory.
echo Ý3) Copy Unforgiven on top of your Moraff's World directory.
echo Ý4) Type 'CONVERT' to run the conversion program from your World directory.
echo Ý
echo ÝNote: Your character will begin as a 0 level 'I can handle anything' player
echo Ý  with no spell points (Unforgiven is a very unforgiving game!).
echo Ý
echo ÝUpgrading from the shareware version of Unforgiven:
echo Ý1) First make a backup copy of your Unforgiven directory.
echo Ý2) Get into your old Unforgiven directory.
echo Ý3) Copy the new Unforgiven on top of your old Unforgiven directory.
echo Ý
echo ÝVITAL NOTE: If the map keeps telling you to 'GO EAST', type 'FIX' at the DOS
echo Ý  prompt to put the special monster back on the map!
