echo off
cls
echo                         SORCERIAN README FILE
echo                            March 24, 1990
echo.
echo.
echo  The intention of this Readme file is to inform you of possible 
echo  problems with the program and updates to the documentation. 
echo.
echo  The following problem has been reported in Version 1.4.
echo.
echo        While located in TOWN you may see an overlay from the previous 
echo        screen (Main Menu).  In order to clear this problem, Save your 
echo        characters and restart game.
echo.
pause

