


echo off

echo  * * * * * * * * * * * * * * * * * * * * * * * * * * * *
echo  *  * * * * * * * * * * * * * * * * * * * * * * * * *  *
echo  *  *                                               *  *
echo  *  *                 HOVER FORCE                   *  *
echo  *  *                                               *  *
echo  *  *                                               *  *
echo  *  *                  Copyright                    *  *
echo  *  *              Astral Software 1990             *  *
echo  *  *                                               *  *
echo  *  * * * * * * * * * * * * * * * * * * * * * * * * *  *
echo  *                                                     *
echo  *                                                     *
echo  *      At the DOS prompt type :-                      *
echo  *                                                     *
echo  *                 E   for the EGA version             *
echo  *                                                     *
echo  *           or    V   for the VGA/MCGA version        *
echo  *                                                     *
echo  *           or    T   for the TANDY version           *
echo  *                                                     *
echo  * * * * * * * * * * * * * * * * * * * * * * * * * * * *
