ECHO OFF
CLS
ECHO --- WELCOME TO UNDERFIRE!
ECHO ---     Please note that the maps are already on this disk.
ECHO --- There is no separate map disk, unlike the 5 1/4"
ECHO --- version, which does. So, when the game prompts you for
ECHO --- the letter of the map/save disk, type in the letter of 
ECHO --- the drive that this disk is in, assuming that you are 
ECHO --- not using some other disk.
ECHO --- 
ECHO ---     Please wait a bit while the game loads.
DR39
UNDERFIR
