@echo off
cls
echo ษออออออออออออออออออออออออออออออออ !AMAZING! 1.1 ออออออออออออออออออออออออออออออป
echo บ                                                                             บ
echo บ       For DOS computers. Requires EGA or VGA graphics. Windows optional.    บ
echo บ       To score points in this game you must successfully work your          บ
echo บ       way through mazes. The better you do the harder the mazes             บ
echo บ       become. The mazes are NEVER the same. Your piece is moved with        บ
echo บ       the direction keys. But every few seconds each key changes.           บ
echo บ       Sometimes the keys move your piece the way they should. Most of       บ
echo บ       the time they don't. Follow the compass to see which key moves        บ
echo บ       which direction. In the Expert game even the maze moves.              บ
echo บ       No one gets wounded... No one dies... Amazing....                     บ
echo บ copyright 1993 by Arthur Wells, Jr.                REGISTRATION FEE: $12.00 บ
echo ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
echo บ   Choose one of the following and then press Enter:                         บ
echo บ                                                                             บ
echo บ           1.) Print the registration form. (It's only $12.00.)              บ
echo บ           2.) Show the instructions on your screen.                         บ
echo บ           3.) Print the instructions.                                       บ
echo บ           4.) Run Amazing.                                                  บ
echo บ           X.) Clear the screen.                                             บ
echo ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
