echo off
cls
echo.
echo.
ECHO .    
ECHO .             ษออออออออออออออออออออออออออออออออออออออออออออออป
ECHO .             บ                                              บ
ECHO .             บ    PRINT " Tegel's Mercenaries " Manual      บ
ECHO .             บ                                              บ
ECHO .             บ BE SURE YOUR PRINTER HAS PAPER AND IS ONLINE บ
ECHO .             บ                                              บ
ECHO .             ศออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO .    
ECHO.
PAUSE
cls
ECHO .
ECHO .    
ECHO .    
ECHO .    
ECHO .    
ECHO .    
ECHO .             ษออออออออออออออออออออออออออออออออออออออออออออออป
ECHO .             บ                                              บ
ECHO .             บ            - PRINTING MANUAL -               บ
ECHO .             บ                                              บ
ECHO .             บ                   FOR                        บ
ECHO .             บ                                              บ
ECHO .             บ            Tegel's Mercenaries               บ
ECHO .             บ                                              บ
echo .             บ                                              บ
ECHO .             ศออออออออออออออออออออออออออออออออออออออออออออออผ
ECHO .    
ECHO .    
ECHO .
ECHO .
ECHO .    
ECHO .    
ECHO .
TYPE \mercs\docs\mercs.doc > LPT1
ECHO .
cls
ECHO .
ECHO .    
ECHO .    
ECHO .
ECHO .
ECHO    Manual print is complete!
PAUSE
CLS

